image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build

before_script:
    - apt update -y -q
    - apt install build-essential -y -q
    - apt install curl -y -q
    - "curl -sL https://deb.nodesource.com/setup_14.x | bash -"
    - apt install nodejs -y -q
    - node --version
    - npm --version
    - "dotnet restore KubernetesDeploymentDemo.sln"

build:
    stage: build
    script:
        - "dotnet build KubernetesDeploymentDemo.sln"
