apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-deployment
spec:
  selector:
    matchLabels:
      app: kdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo
    spec:
      containers:
      - name: kdemo-customer-api
        image: kdemo-customer-api:latest
        imagePullPolicy: Never #to pull local image
        ports:
        - containerPort: 80