apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-customer-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-customer-api
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-customer-api
    spec:
      containers:
      - name: kdemo-customer-api
        image: kdemo-customer-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-catalog-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-catalog-api
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-catalog-api
    spec:
      containers:
        - name: kdemo-catalog-api
          image: kdemo-catalog-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-orders-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-orders-api
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-orders-api
    spec:
      containers:
        - name: kdemo-orders-api
          image: kdemo-orders-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-orders--service-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-orders-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-orders-service
    spec:
      containers:
        - name: kdemo-orders-service
          image: kdemo-orders-service:latest
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-db-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-db
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-db
    spec:
      containers:
        - name: kdemo-db
          image: kdemo-db
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: admin!@#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-rabbitmq-deployment
  labels:
    app: kdemo
spec:
  selector:
    matchLabels:
      app: kdemo-rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: kdemo-rabbitmq
    spec:
      containers:
        - name: kdemo-rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_PASS
              value: admin