version: '3.4'

services:
  kdemo.webapp:
    image: kdemo.webapp
    build:
      context: .
      dockerfile: web/WebApp/Dockerfile
  
  kdemo.documents.api:
    image: kdemo.documents.api
    build:
      context: .
      dockerfile: api/Documents.Api/Dockerfile
  
  kdemo.controller:
    image: kdemo.controller
    build:
      context: .
      dockerfile: service/Controller/Dockerfile
  
  kdemo.driver:
    image: kdemo.driver
    build:
      context: .
      dockerfile: sources/Driver/Dockerfile

  kdemo.sql.data:
    image: kdemo.sql.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5433:5432"

  kdemo.rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin