version: '3.4'

services:
  webclient:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  driver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  controller:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  documents.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

