version: '3.4'

services:
#  kdemo.webapp:
#    image: kdemo.webapp
#    build:
#      context: .
#      dockerfile: web/WebApp/Dockerfile

  post-api:
    image: post-api
    build:
      context: .
      dockerfile: api/Posts.API/Dockerfile
    depends_on:
      - rabbitmq
      - sql-data
    restart: on-failure

  posts-wiki:
    image: posts-wiki
    build:
      context: .
      dockerfile: sources/Posts.Wiki/Dockerfile
    depends_on:
      - rabbitmq
      - post-api
    restart: on-failure

  posts-reddit:
    image: posts-reddit
    build:
      context: .
      dockerfile: sources/Posts.Reddit/Dockerfile
    depends_on:
      - rabbitmq
      - post-api
    restart: on-failure

  sql-data:
    image: sql-data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 10