version: '3.4'

services:
  kdemo.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  kdemo.driver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  kdemo.controller:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  kdemo.documents.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

