version: '3.4'

services:
    post-api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
        - DbRetryCount=${DB_RETRY}
      ports:
        - "8081:80"

    posts-reddit:
      environment:
        - DOTNET_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
        
    posts-wiki:
      environment:
        - DOTNET_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}

    sql-data:
      ports:
        - "5433:5432"
      
    rabbitmq:
      ports:
        - "15673:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}