version: '3.4'

services:
    kdemo.webapp:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
      ports:
        - "8080:80"

    kdemo.posts.api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
      ports:
        - "8081:80"
      depends_on:
        - kdemo.rabbitmq

    kdemo.posts.reddit:
      environment:
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
      depends_on:
        - kdemo.rabbitmq
        
    kdemo.posts.wiki:
      environment:
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
      depends_on:
        - kdemo.rabbitmq

    kdemo.rabbitmq:
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}