version: '3.4'

services:
  kdemo.webapp:
    image: kdemo.webapp
    build:
      context: .
      dockerfile: web/WebApp/Dockerfile

  kdemo.posts.api:
    image: kdemo.posts.api
    build:
      context: .
      dockerfile: api/Posts.API/Dockerfile

  kdemo.controller:
    image: kdemo.controller
    build:
      context: .
      dockerfile: service/Controller/Dockerfile

  kdemo.posts.wiki:
    image: kdemo.posts.wiki
    build:
      context: .
      dockerfile: sources/Posts.Wiki/Dockerfile
    depends_on:
      - kdemo.rabbitmq

  kdemo.posts.reddit:
    image: kdemo.posts.reddit
    build:
      context: .
      dockerfile: sources/Posts.Reddit/Dockerfile
    depends_on:
      - kdemo.rabbitmq

  kdemo.sql.data:
    image: kdemo.sql.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5433:5432"

  kdemo.rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
    expose:
      - "5672"