version: '3.4'

services:
#    kdemo.webapp:
#      environment:
#        - ASPNETCORE_ENVIRONMENT=Production
#      ports:
#        - "8080:80"

    post-api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
        - DbRetryCount=${DB_RETRY}
      ports:
        - "8081:80"

    posts-reddit:
      environment:
        - DOTNET_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}
        
    posts-wiki:
      environment:
        - DOTNET_ENVIRONMENT=Production
        - EventBusConnection=${SERVICE_BUS}
        - EventBusUserName=${RABBIT_USERNAME}
        - EventBusPassword=${RABBIT_PASS}
        - EventBusPort=${RABBIT_PORT}
        - EventBusRetryCount=${RABBIT_RETRY}

    rabbitmq:
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBIT_USERNAME}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}