version: '3.4'

services:
#  kdemo.webapp:
#    image: kdemo.webapp
#    build:
#      context: .
#      dockerfile: web/WebApp/Dockerfile

  kdemo.posts.api:
    image: kdemo.posts.api
    build:
      context: .
      dockerfile: api/Posts.API/Dockerfile
    depends_on:
      - kdemo.rabbitmq
      - kdemo.sql.data
    restart: on-failure

  kdemo.posts.wiki:
    image: kdemo.posts.wiki
    build:
      context: .
      dockerfile: sources/Posts.Wiki/Dockerfile
    depends_on:
      - kdemo.rabbitmq
      - kdemo.posts.api
    restart: on-failure

  kdemo.posts.reddit:
    image: kdemo.posts.reddit
    build:
      context: .
      dockerfile: sources/Posts.Reddit/Dockerfile
    depends_on:
      - kdemo.rabbitmq
      - kdemo.posts.api
    restart: on-failure

  kdemo.sql.data:
    image: kdemo.sql.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    expose:
      - "5432"

  kdemo.rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 10