version: '3.4'

services:
  kdemo.webapp:
    image: kdemo.webapp
    build:
      context: ./web/WebApp
      dockerfile: Dockerfile
    volumes:
      - ./web/WebApp/bin/pub/:/app
    container_name: kdemo.webapp
    ports: 
      - "8080:80"
    depends_on:
      - kdemo.documents.api

  kdemo.driver:
    image: kdemo.driver
    build:
      context: ./sources/Driver
      dockerfile: Dockerfile
    volumes:
      - ./sources/Driver/bin/pub/:/app
    container_name: kdemo.driver
    ports: 
      - "8082:80"
    depends_on:
      - kdemo.rabbitmq

  kdemo.controller:
    image: kdemo.controller
    build:
      context: ./service/Controller
      dockerfile: Dockerfile
    volumes:
      - ./service/Controller/bin/pub/:/app
    container_name: kdemo.controller
    ports: 
      - "8083:80"
    depends_on:
      - kdemo.rabbitmq

  kdemo.documents.api:
    image: kdemo.documents.api
    build:
      context: ./api/Documents.Api
      dockerfile: Dockerfile
    volumes:
      - ./api/Documents.Api/bin/pub/:/app
    container_name: kdemo.documents.api
    ports: 
      - "8081:80"
    depends_on:
      - kdemo.sql.data
      - kdemo.rabbitmq

  kdemo.sql.data:
    image: kdemo.sql.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5433"
    container_name: kdemo.sql.data

  kdemo.rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: kdemo.rabbitmq