version: '3.4'

services:
  kdemo-customer-api:
    image: kdemo-customer-api
    build:
      context: .
      dockerfile: api/Customer.Api/Dockerfile
    restart: on-failure
    env_file: .env
    networks:
      - main-network
    depends_on:
      - kdemo-postgres
      - kdemo-rabbitmq
  kdemo-catalog-api:
   image: kdemo-catalog-api
   build:
     context: .
     dockerfile: api/Catalog.Api/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   depends_on:
     - kdemo-postgres
     - kdemo-rabbitmq
  kdemo-orders-api:
   image: kdemo-orders-api
   build:
     context: .
     dockerfile: api/Orders.Api/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   depends_on:
     - kdemo-postgres
     - kdemo-rabbitmq
  kdemo-orders-service:
   image: kdemo-orders-service
   build:
     context: .
     dockerfile: services/Service.Orders/Dockerfile
   restart: on-failure
   env_file: .env
   networks:
     - main-network
   depends_on:
     - kdemo-postgres
     - kdemo-rabbitmq
  kdemo-nginx:
    image: nginx:alpine
    hostname: 'kdemo-nginx'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - '10100:80'
      - '10101:8080'
    depends_on:
      - kdemo-orders-api
      - kdemo-catalog-api
      - kdemo-customer-api
    restart: always
    networks:
      - main-network
  kdemo-web:
    image: kdemo-web
    build:
      context: web
      dockerfile: prod.dockerfile
    env_file: .env
    restart: on-failure
    depends_on:
      - kdemo-nginx
    networks:
      - main-network

  kdemo-postgres:
   image: kdemo-postgres
   build:
     context: ./database
     dockerfile: Dockerfile
   env_file: .env
   networks:
      - main-network
   volumes:
     - "kdemo-postgres-data:/var/lib/postgresql/data"
  kdemo-rabbitmq:
     image: rabbitmq:3-management
     env_file: .env
     networks:
       - main-network
  kdemo-elastic:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    volumes:
      - kdemo-elastic-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - main-network
  kdemo-kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.2
    depends_on:
      - kdemo-elastic
    environment:
      - ELASTICSEARCH_URL=http://kdemo-elastic:9200
    networks:
      - main-network

networks:
   main-network:
     driver: bridge
     
volumes:
  kdemo-postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/dev/projects-data/kdemo-postgres
  kdemo-elastic-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/dev/projects-data/kdemo-elastic