version: '3.4'

services:
  webclient:
    image: webclient
    build:
      context: ./web/WebClient
      dockerfile: Dockerfile
    volumes:
      - ./web/WebClient/bin/pub/:/app
    container_name: webclient
    ports: 
      - "8080:80"
    depends_on:
      - documents.api

  driver:
    image: driver
    build:
      context: ./sources/Driver
      dockerfile: Dockerfile
    volumes:
      - ./sources/Driver/bin/pub/:/app
    container_name: driver
    ports: 
      - "8082:80"
    depends_on:
      - rabbitmq

  controller:
    image: controller
    build:
      context: ./service/Controller
      dockerfile: Dockerfile
    volumes:
      - ./service/Controller/bin/pub/:/app
    container_name: controller
    ports: 
      - "8083:80"
    depends_on:
      - rabbitmq

  documents.api:
    image: documents.api
    build:
      context: ./api/Documents.Api
      dockerfile: Dockerfile
    volumes:
      - ./api/Documents.Api/bin/pub/:/app
    container_name: documents.api
    ports: 
      - "8081:80"
    depends_on:
      - sql.data
      - rabbitmq

  sql.data:
    image: sql.data
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    container_name: sql.data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    container_name: rabbitmq