apiVersion: v1
kind: Service
metadata:
  name: kdemo-customer-api
  labels:
    app: kdemo
spec:
  type: LoadBalancer
  selector:
    app: kdemo-customer-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-catalog-api
  labels:
    app: kdemo
spec:
  type: LoadBalancer
  selector:
    app: kdemo-catalog-api
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-orders-api
  labels:
    app: kdemo
spec:
  type: LoadBalancer
  selector:
    app: kdemo-orders-api
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-db
  labels:
    app: kdemo
spec:
  type: ClusterIP
  selector:
    app: kdemo-db
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-rabbitmq
  labels:
    app: kdemo
spec:
  type: ClusterIP
  selector:
    app: kdemo-rabbitmq
  ports:
    - port: 5672
