apiVersion: v1
kind: Service
metadata:
  name: kdemo-customer-api
spec:
  selector:
    app: kdemo
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-customers-db
spec:
  selector:
    app: kdemo
  ports:
    - protocol: TCP
      port: 5432