apiVersion: v1
kind: Service
metadata:
  name: kdemo-customer-api-service
spec:
  type: LoadBalancer
  selector:
    app: kdemo-customer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-catalog-api-service
spec:
  type: LoadBalancer
  selector:
    app: kdemo-catalog
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-orders-api-service
spec:
  type: LoadBalancer
  selector:
    app: kdemo-orders
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kdemo-postgres-service
spec:
  type: ClusterIP
  selector:
    app: kdemo-postgres
  ports:
    - port: 5432
