// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Orders.Api.Database;

namespace Orders.Api.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Orders.Api.Database.Models.OrderDto", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .UseIdentityByDefaultColumn();

                b.Property<Guid>("CustomerGuid")
                    .HasColumnType("uuid");

                b.Property<Guid>("Guid")
                    .HasColumnType("uuid");

                b.Property<Guid[]>("ItemGuids")
                    .HasColumnType("uuid[]");

                b.Property<DateTime>("UpdatedTime")
                    .HasColumnType("timestamp without time zone");

                b.HasKey("Id");

                b.ToTable("Orders");
            });
#pragma warning restore 612, 618
        }
    }
}