--
-- PostgreSQL database dump
--

-- Dumped from database version 13.1 (Debian 13.1-1.pgdg100+1)
-- Dumped by pg_dump version 13.1

-- Started on 2021-01-31 10:24:51 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS "kdemo-customers";
--
-- TOC entry 2950 (class 1262 OID 16710)
-- Name: kdemo-customers; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE "kdemo-customers" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE "kdemo-customers" OWNER TO admin;

\connect -reuse-previous=on "dbname='kdemo-customers'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16718)
-- Name: Customers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Customers" (
    "Id" bigint NOT NULL,
    "Guid" uuid NOT NULL,
    "FirstName" text,
    "LastName" text,
    "Email" text,
    "Gender" text,
    "UpdatedTime" timestamp without time zone NOT NULL
);


ALTER TABLE public."Customers" OWNER TO admin;

--
-- TOC entry 201 (class 1259 OID 16716)
-- Name: Customers_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Customers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Customers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 200 (class 1259 OID 16711)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- TOC entry 2944 (class 0 OID 16718)
-- Dependencies: 202
-- Data for Name: Customers; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."Customers" ("Id", "Guid", "FirstName", "LastName", "Email", "Gender", "UpdatedTime") FROM stdin;
1	24183b3d-196e-4695-887b-606d72ab042a	Justis	Sibley	jsibley0@wp.com	Bigender	0001-01-01 00:00:00
28	ea6be99f-7279-4782-b54f-3ecfa3e2d2c1	Zorina	Sansom	zsansomr@php.net	Male	0001-01-01 00:00:00
29	7cdf841e-31db-4aa6-a13d-fe19603b4c43	Ravid	Ventum	rventums@163.com	Female	0001-01-01 00:00:00
30	c048abcc-cb27-4c17-ae20-c238750d1d18	Willie	Pidgin	wpidgint@redcross.org	Genderqueer	0001-01-01 00:00:00
31	364c5ca3-e642-44ff-8e53-6365e46b728a	Lora	Wasielewski	lwasielewskiu@merriam-webster.com	Male	0001-01-01 00:00:00
32	79d39fe7-a46d-4f60-bb55-3d3d78491467	Knox	Gapper	kgapperv@tuttocitta.it	Genderfluid	0001-01-01 00:00:00
33	3768d14b-45f7-4dfb-b0d7-0ccf5c0d47d5	Fulton	Bartolommeo	fbartolommeow@issuu.com	Male	0001-01-01 00:00:00
34	318b7966-a974-4b8c-9011-67d220f9a1ca	Simona	Klebes	sklebesx@opera.com	Genderfluid	0001-01-01 00:00:00
35	d2eb436c-f88b-4af4-a3ba-64c13cf18823	Kelci	Bulch	kbulchy@goo.gl	Genderfluid	0001-01-01 00:00:00
36	232dad51-34b1-4648-be8f-2fb21e025c69	Lonnie	Ricket	lricketz@networksolutions.com	Genderfluid	0001-01-01 00:00:00
37	479ed05f-85d5-48e2-8b70-4be1ef1e4228	Norean	Milthorpe	nmilthorpe10@utexas.edu	Genderfluid	0001-01-01 00:00:00
38	e35caae3-ecec-46f8-a4fb-4aa82ed13637	Sue	Howlett	showlett11@yandex.ru	Genderfluid	0001-01-01 00:00:00
39	d491b9c3-b631-4a17-b799-e94e4e0cb94f	Sidnee	Leser	sleser12@theglobeandmail.com	Bigender	0001-01-01 00:00:00
40	89e58be5-9156-44c2-8ccb-4490a57823ee	Cynthie	Strettell	cstrettell13@123-reg.co.uk	Agender	0001-01-01 00:00:00
41	2b8115fc-4396-430e-ab7c-c344d2fe8765	Tome	Doggett	tdoggett14@amazon.co.uk	Bigender	0001-01-01 00:00:00
42	7b1f767a-0ec9-48a9-9f26-6b488b85d068	Tiertza	Paget	tpaget15@rakuten.co.jp	Genderfluid	0001-01-01 00:00:00
43	11e49fce-0513-4280-a3bc-a6907a39ef85	Wolfie	Medford	wmedford16@baidu.com	Agender	0001-01-01 00:00:00
44	ad1f0ae9-af27-48c8-8754-676021fae2c7	Galvin	Keuneke	gkeuneke17@reference.com	Agender	0001-01-01 00:00:00
45	e486a6c4-6d5b-4c36-9ec7-1b409da071e0	Lainey	Patis	lpatis18@multiply.com	Genderfluid	0001-01-01 00:00:00
46	40bc03c7-8aaa-449f-9d66-2512450528c8	Domini	Brumbye	dbrumbye19@is.gd	Genderfluid	0001-01-01 00:00:00
47	1ca792eb-bda3-497b-9de7-5b9c528d35a4	Prentiss	MacDougall	pmacdougall1a@w3.org	Bigender	0001-01-01 00:00:00
48	43212be8-e609-44b5-b94f-a1fc1f3009f3	Sheri	Colaco	scolaco1b@weibo.com	Agender	0001-01-01 00:00:00
27	48954833-1a02-46a3-991d-8740fa54044f	Adolph	Chicken	achickenq@blog.com	Genderqueer	0001-01-01 00:00:00
26	6372ee25-9041-4caf-a60c-edfed53e0c83	Donnell	Rikkard	drikkardp@yahoo.co.jp	Female	0001-01-01 00:00:00
25	606d07b8-f102-49a3-a1fe-2b77b9938307	Darcee	Breche	dbrecheo@stanford.edu	Agender	0001-01-01 00:00:00
24	4e90733a-d887-4c03-b91f-f22167ffc3a3	Selina	Popworth	spopworthn@cbslocal.com	Non-binary	0001-01-01 00:00:00
2	7401a43e-46a4-4d3e-9f2c-a53f4fa546ca	Nev	Hubbart	nhubbart1@amazon.co.uk	Male	0001-01-01 00:00:00
3	f47d70a5-92d9-4e40-92ab-901625f08091	Richardo	Steynor	rsteynor2@washingtonpost.com	Female	0001-01-01 00:00:00
4	66e8fa52-f015-474c-9342-549347ffe69a	Guenevere	Deeprose	gdeeprose3@studiopress.com	Female	0001-01-01 00:00:00
5	5e586b3b-7ffc-4e39-bb41-0dca659e54cf	Wynn	Allonby	wallonby4@fotki.com	Male	0001-01-01 00:00:00
6	92b6d64b-1335-4bb7-a58e-c0d4fecf0260	Andre	Brede	abrede5@timesonline.co.uk	Non-binary	0001-01-01 00:00:00
7	b0312cfc-b42f-43fd-a9c2-59e2caafb02a	Willdon	McCotter	wmccotter6@bravesites.com	Bigender	0001-01-01 00:00:00
8	4422eed3-c90d-4726-a20c-64fc2ca6a049	Madlin	Raymond	mraymond7@howstuffworks.com	Male	0001-01-01 00:00:00
9	6a65484e-dc0c-4956-89d3-9b9104006974	Garwin	Espino	gespino8@ycombinator.com	Male	0001-01-01 00:00:00
10	7a566d8c-c64a-49d7-a107-25a1f6fa3668	Hieronymus	Stennes	hstennes9@chicagotribune.com	Non-binary	0001-01-01 00:00:00
11	4f76c895-e9b0-4036-b0f7-24ea07aff553	Lacie	McGarry	lmcgarrya@mtv.com	Female	0001-01-01 00:00:00
49	0f8054d2-cae5-4516-96db-2c3658d4bd79	Millard	Sabbin	msabbin1c@google.ca	Agender	0001-01-01 00:00:00
12	f758423e-8547-468c-a898-fdd69958d79a	Rosaline	Stembridge	rstembridgeb@webs.com	Agender	0001-01-01 00:00:00
14	82f10b12-695d-431f-8397-2a0eadccefbf	Siffre	Ballin	sballind@smugmug.com	Genderqueer	0001-01-01 00:00:00
15	039a9be8-b5d5-4640-9ecc-da09046ae53a	Adelle	Pulhoster	apulhostere@springer.com	Bigender	0001-01-01 00:00:00
16	35e642a5-13bc-4d1d-8a84-705e4532fdb1	Valeda	McGauhy	vmcgauhyf@dmoz.org	Female	0001-01-01 00:00:00
17	6990b88d-b5ae-4811-9603-4a920920ae76	Horatia	Kubelka	hkubelkag@home.pl	Bigender	0001-01-01 00:00:00
18	225521f6-ea2b-4e0c-be3a-c24d46ab83f5	Emmalyn	Bangs	ebangsh@networksolutions.com	Genderfluid	0001-01-01 00:00:00
19	d5f57e15-b2a7-4057-916f-731ab49a6f43	Andres	Hallard	ahallardi@smh.com.au	Male	0001-01-01 00:00:00
20	6c9d711d-59af-421c-b297-8bfb0a168362	Juditha	Arens	jarensj@tripod.com	Agender	0001-01-01 00:00:00
21	74a28896-ca74-4353-95ec-894c7c59244c	Ermentrude	Isoldi	eisoldik@ebay.co.uk	Female	0001-01-01 00:00:00
22	8cbde2d2-4e7c-4404-acac-fcb26b974d0f	Matty	Curphey	mcurpheyl@kickstarter.com	Polygender	0001-01-01 00:00:00
23	ab13db04-1a86-4644-995f-7fed9e746fcd	Sheffie	Julyan	sjulyanm@so-net.ne.jp	Polygender	0001-01-01 00:00:00
13	a359d78f-d33a-4ec5-bc97-43bef6c0e895	Mirna	Ishak	mishakc@huffingtonpost.com	Non-binary	0001-01-01 00:00:00
50	2ff851dd-9954-463f-83c2-82d46205432a	Dorelle	Skaif	dskaif1d@so-net.ne.jp	Male	0001-01-01 00:00:00
\.


--
-- TOC entry 2942 (class 0 OID 16711)
-- Dependencies: 200
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20210131094106_Init	5.0.2
\.


--
-- TOC entry 2951 (class 0 OID 0)
-- Dependencies: 201
-- Name: Customers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public."Customers_Id_seq"', 51, false);


--
-- TOC entry 2811 (class 2606 OID 16725)
-- Name: Customers PK_Customers; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Customers"
    ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("Id");


--
-- TOC entry 2809 (class 2606 OID 16715)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2021-01-31 10:24:52 UTC

--
-- PostgreSQL database dump complete
--

