apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-customer-api-deployment
  namespace: kdemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kdemo-customer-api
  template:
    metadata:
      labels:
        app: kdemo-customer-api
    spec:
      containers:
        - name: kdemo-customer-api
          image: registry.ezlab.ru/ezlab/kubernetesdeploymentdemo/kdemo-customer-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: Production
            - name: "DOTNET_ENVIRONMENT"
              value: Production
            - name: "Elastic__Uri"
              value: "$EZLAB_ELASTIC_STAGING"
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-catalog-api-deployment
  namespace: kdemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kdemo-catalog-api
  template:
    metadata:
      labels:
        app: kdemo-catalog-api
    spec:
      containers:
        - name: kdemo-catalog-api
          image: registry.ezlab.ru/ezlab/kubernetesdeploymentdemo/kdemo-catalog-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: Production
            - name: "DOTNET_ENVIRONMENT"
              value: Production
            - name: "Elastic__Uri"
              value: "$EZLAB_ELASTIC_STAGING"
      imagePullSecrets:
        - name: registry-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-orders-api-deployment
  namespace: kdemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kdemo-orders-api
  template:
    metadata:
      labels:
        app: kdemo-orders-api
    spec:
      containers:
        - name: kdemo-orders-api
          image: registry.ezlab.ru/ezlab/kubernetesdeploymentdemo/kdemo-orders-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: Production
            - name: "DOTNET_ENVIRONMENT"
              value: Production
            - name: "Elastic__Uri"
              value: "$EZLAB_ELASTIC_STAGING"
      imagePullSecrets:
        - name: registry-credentials