kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdemo-elastic-pv-claim
  labels:
    app: kdemo-elastic
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi