apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-elastic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdemo-elastic
  template:
    metadata:
      labels:
        app: kdemo-elastic
    spec:
      initContainers:
        - name: file-permissions
          image: busybox
          command: [ 'chown', '-R', '1000:1000', '/usr/share/elasticsearch/' ]
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data
          securityContext:
            privileged: true
            runAsUser: 0
        - name: increase-vm-max-map
          image: busybox
          command: [ "sysctl", "-w", "vm.max_map_count=262144" ]
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: [ "sh", "-c", "ulimit -n 65536" ]
          securityContext:
            privileged: true
      containers:
        - name: kdemo-elastic
          image: elasticsearch:8.4.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          env:
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
            - name: "xpack.watcher.enabled"
              value: "false"
            - name: "xpack.security.enabled"
              value: "false"
            - name: "discovery.type"
              value: "single-node"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data
      volumes:
        - name: elastic-data
          persistentVolumeClaim:
            claimName: kdemo-elastic-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-kibana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdemo-kibana
  template:
    metadata:
      labels:
        app: kdemo-kibana
    spec:
      containers:
        - name: kdemo-kibana
          image: kibana:8.4.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: "http://kdemo-elastic:9200"
            - name: ELASTICSEARCH_HOSTS
              value: "http://kdemo-elastic:9200"
            - name: SERVER_PUBLICBASEURL
              value: "https://metrics.kdemo.staging.codegarage.ru/"  