apiVersion: v1
kind: Service
metadata:
  name: kdemo-nginx
  namespace: kdemo
  labels:
    app: kdemo-nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: kdemo-nginx
