apiVersion: v1
kind: ConfigMap
metadata:
  name: kdemo-nginx-config
  namespace: kdemo
data:
  proxy.conf: |
    proxy_redirect          off;
    proxy_http_version      1.1;
    proxy_set_header        Upgrade             $http_upgrade;
    proxy_cache_bypass      $http_upgrade;
    proxy_set_header        Connection          keep-alive;
    proxy_set_header        Host $host;
    proxy_set_header        X-Real-IP           $remote_addr;
    proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto   $scheme;
    proxy_set_header        X-Forwarded-Host    $server_name;

  nginx.conf: |
    user nginx;

    worker_processes    auto;

    events { worker_connections 1024; }

    http {
        include             /etc/nginx/proxy.conf;
        include             /etc/nginx/mime.types;
        access_log /dev/stdout;
        error_log /dev/stdout;
    
        upstream frontend {
                server          kdemo-web;
        }
    
        upstream customer-api {
            server          kdemo-customer-api:8080;
        }

        upstream orders-api {
            server          kdemo-orders-api:8080;
        }

        upstream catalog-api {
            server          kdemo-catalog-api:8080;
        }

        server {
            listen          80;
            server_name     $hostname;

            location /api/customers {
                resolver 127.0.0.11 ipv6=off;
                proxy_pass  http://customer-api;
            }

            location /api/orders {
                resolver 127.0.0.11 ipv6=off;
                proxy_pass  http://orders-api;
            }

            location /api/catalog {
                resolver 127.0.0.11 ipv6=off;
                proxy_pass  http://catalog-api;
            }
    
            location / {
                 resolver 127.0.0.11 ipv6=off;
                        proxy_pass  http://frontend;
            }    
        }
    }
