kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdemo-postgres-pv-claim
  namespace: kdemo
  labels:
    app: kdemo-postgres
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi