apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdemo-postgres
  template:
    metadata:
      labels:
        app: kdemo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: kdemo-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: kdemo-postgres-pv-claim