kind: PersistentVolume
apiVersion: v1
metadata:
  name: kdemo-postgres-pv-volume
  labels:
    type: local
    app: kdemo-postgres
spec:
  storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdemo-postgres-pv-claim
  labels:
    app: kdemo-postgres
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi