kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kdemo-postgres-pv-claim
  namespace: kdemo
  labels:
    app: kdemo-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path