apiVersion: v1
kind: Service
metadata:
  name: kdemo-rabbitmq
  namespace: kdemo
  labels:
    app: kdemo-rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
  selector:
    app: kdemo-rabbitmq