apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-orders-service-deployment
  namespace: kdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdemo-orders-service
  template:
    metadata:
      labels:
        app: kdemo-orders-service
    spec:
      containers:
        - name: kdemo-orders-service
          image: registry.ezlab.ru/ezlab/kubernetesdeploymentdemo/kdemo-orders-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: Production
      imagePullSecrets:
        - name: registry-credentials