apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdemo-web-deployment
  namespace: kdemo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kdemo-web
  template:
    metadata:
      labels:
        app: kdemo-web
    spec:
      containers:
        - name: kdemo-web
          image: registry.ezlab.ru/ezlab/kubernetesdeploymentdemo/kdemo-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: kdemo-web-config
      imagePullSecrets:
        - name: registry-credentials