// <auto-generated />
using System;
using Catalog.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Api.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20250303070040_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Api.Database.Models.CatalogCategoryDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                    
                    b.HasData(
                        new 
                        {
                            Id = 1,
                            Guid = new Guid("cc864b30-940a-43be-88f0-e032ea52c466"),
                            Description = "Specialty Food",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 4, 618, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Guid = new Guid("d1a02318-ba6c-4ad8-a72d-fdadb37e31d9"),
                            Description = "Groceries",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 880, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Guid = new Guid("fb8e923b-6404-4a7a-8c17-9908d7809a74"),
                            Description = "Beverages",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 66, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Guid = new Guid("8165cd89-b2d3-4c67-b832-53ce397336f1"),
                            Description = "Laptops",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 213, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Guid = new Guid("cc04f5aa-2abd-4a2a-900b-a5a6531f3f32"),
                            Description = "Tablets",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 562, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Guid = new Guid("819b1e57-0334-4e5a-a6dd-cff70891deb1"),
                            Description = "Shoes",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 857, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Guid = new Guid("75f65800-aeed-4bf6-ba8e-b70323ef1f62"),
                            Description = "Watches",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 21, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Guid = new Guid("21ed387d-9e68-4d1b-8fd5-58755115f7e4"),
                            Description = "Headphones",
                            UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 905, DateTimeKind.Utc)
                        }
                    );
                });

            modelBuilder.Entity("Catalog.Api.Database.Models.CatalogItemDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<double>("Cost")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                    
                    b.HasData(
                new { Id = 1, Guid = new Guid("0fe69a5f-0978-4b46-92a3-4b33b12bca78"), Description = "Artisanal foods", Cost = 9256, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 8, 570, DateTimeKind.Utc) },
                new { Id = 2, Guid = new Guid("4a66a7db-ee8d-4e15-9415-dc05a0922719"), Description = "Caviar", Cost = 9962, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 838, DateTimeKind.Utc) },
                new { Id = 3, Guid = new Guid("321a2def-3dae-41c7-a83e-fba02f2cdcb0"), Description = "Cheese and artisan cheese", Cost = 8326, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 853, DateTimeKind.Utc) },
                new { Id = 4, Guid = new Guid("c3d95088-4cbd-45ee-b6a3-aa87f7f37c35"), Description = "Specialty coffee", Cost = 569, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 863, DateTimeKind.Utc) },
                new { Id = 5, Guid = new Guid("2c94c829-0bf1-4951-abdf-0621f4ffb5bb"), Description = "High-quality chocolate", Cost = 1914, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 869, DateTimeKind.Utc) },
                new { Id = 6, Guid = new Guid("b706e37c-eed0-4f79-a916-448a4ce5789e"), Description = "Foie gras", Cost = 8035, CategoryId = 1, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 873, DateTimeKind.Utc) },
                new { Id = 7, Guid = new Guid("7b711d89-d7b8-4981-ad00-458097c9db76"), Description = "Asparagus", Cost = 278, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 884, DateTimeKind.Utc) },
                new { Id = 8, Guid = new Guid("49367a5d-6ddf-4853-9446-785e3af2fb8c"), Description = "Broccoli", Cost = 2521, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 894, DateTimeKind.Utc) },
                new { Id = 9, Guid = new Guid("8f8a139d-508f-4437-818c-07558d817773"), Description = "Carrots", Cost = 3418, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 897, DateTimeKind.Utc) },
                new { Id = 10, Guid = new Guid("ee54fc0a-a95b-4811-82a8-46729629f9ea"), Description = "Cauliflower", Cost = 4315, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 901, DateTimeKind.Utc) },
                new { Id = 11, Guid = new Guid("81684e65-faa6-4946-8c59-ace4d6864913"), Description = "Celery", Cost = 5212, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 906, DateTimeKind.Utc) },
                new { Id = 12, Guid = new Guid("3af623f6-4024-4061-b4a3-c7843c5e18a2"), Description = "Corn", Cost = 6557, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 912, DateTimeKind.Utc) },
                new { Id = 13, Guid = new Guid("42be8648-7027-40b0-9238-3f5dbf603b0e"), Description = "Cucumbers", Cost = 7454, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 916, DateTimeKind.Utc) },
                new { Id = 14, Guid = new Guid("e64eb646-f894-441e-bba5-9e906dd83595"), Description = "Lettuce / Greens", Cost = 3575, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 921, DateTimeKind.Utc) },
                new { Id = 15, Guid = new Guid("08efb25c-955e-49ac-8e27-9a0a511ca920"), Description = "Mushrooms", Cost = 4472, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 925, DateTimeKind.Utc) },
                new { Id = 16, Guid = new Guid("c0e175e5-957a-435a-9b59-3b77f3d263d6"), Description = "Onions", Cost = 594, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 929, DateTimeKind.Utc) },
                new { Id = 17, Guid = new Guid("649fb5db-ac65-4624-baa6-d2a2ef106174"), Description = "Peppers", Cost = 1491, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 934, DateTimeKind.Utc) },
                new { Id = 18, Guid = new Guid("b367f6c1-5e9c-4802-96ed-cc1069f02af6"), Description = "Potatoes", Cost = 7612, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 939, DateTimeKind.Utc) },
                new { Id = 19, Guid = new Guid("aa0d0b55-6454-4c36-b2bd-5b1fa953fb59"), Description = "Spinach", Cost = 8957, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 945, DateTimeKind.Utc) },
                new { Id = 20, Guid = new Guid("e8f62cd1-7896-4865-a77f-6605d33b3733"), Description = "Squash", Cost = 5079, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 950, DateTimeKind.Utc) },
                new { Id = 21, Guid = new Guid("c3a00185-50e2-4aba-b1ca-277c82f1e986"), Description = "Zucchini", Cost = 6424, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 956, DateTimeKind.Utc) },
                new { Id = 22, Guid = new Guid("440bd027-925e-470b-8eb2-24b1c3d312a2"), Description = "Tomatoes", Cost = 7321, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 961, DateTimeKind.Utc) },
                new { Id = 23, Guid = new Guid("85a6d8c1-ff9e-40bd-8006-c38014d26785"), Description = "Bacon / Sausage", Cost = 3443, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 965, DateTimeKind.Utc) },
                new { Id = 24, Guid = new Guid("6a021aa7-3ba7-447f-a43f-414f123d4172"), Description = "Beef", Cost = 4788, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 971, DateTimeKind.Utc) },
                new { Id = 25, Guid = new Guid("c5b5de2e-71cb-4e31-9e3f-fb00ab51ba97"), Description = "Chicken", Cost = 910, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 976, DateTimeKind.Utc) },
                new { Id = 26, Guid = new Guid("7ddeb477-26b0-4110-af8d-a7f62f169a09"), Description = "Ground beef / Turkey", Cost = 7030, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 981, DateTimeKind.Utc) },
                new { Id = 27, Guid = new Guid("ce6c3acd-bfb6-4df3-b645-be59ec073edf"), Description = "Ham / Pork", Cost = 3152, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 986, DateTimeKind.Utc) },
                new { Id = 28, Guid = new Guid("feb053b4-61b6-48e7-a1dc-3dbed8c7a99b"), Description = "Hot dogs", Cost = 4497, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 992, DateTimeKind.Utc) },
                new { Id = 29, Guid = new Guid("a114a48c-fd02-4f9a-a898-dc2a37ca6c55"), Description = "Lunchmea", Cost = 5843, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 9, 998, DateTimeKind.Utc) },
                new { Id = 30, Guid = new Guid("7e747c4c-e690-4bdf-8850-e0e4aeebd42d"), Description = "Applesauce", Cost = 2935, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 4, DateTimeKind.Utc) },
                new { Id = 31, Guid = new Guid("6253df2c-54d1-4d6c-82c6-fbdf69e8aeff"), Description = "Baked beans", Cost = 4281, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 10, DateTimeKind.Utc) },
                new { Id = 32, Guid = new Guid("31b3db80-03f4-470d-afa2-f917489f32cc"), Description = "Chili", Cost = 851, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 18, DateTimeKind.Utc) },
                new { Id = 33, Guid = new Guid("8e8f26a3-dd6c-418b-9049-18254569373a"), Description = "Fruit", Cost = 2196, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 23, DateTimeKind.Utc) },
                new { Id = 34, Guid = new Guid("3541ad58-9d24-44c0-8093-12344fe47b18"), Description = "Olives", Cost = 3542, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 30, DateTimeKind.Utc) },
                new { Id = 35, Guid = new Guid("fa6794ed-e71c-40d5-9633-4aeb71450b9a"), Description = "Tinned meats", Cost = 4887, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 35, DateTimeKind.Utc) },
                new { Id = 36, Guid = new Guid("5a3820d8-9aa5-48ac-87e7-b8fd0670cf50"), Description = "Tuna / Chicken", Cost = 6232, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 41, DateTimeKind.Utc) },
                new { Id = 37, Guid = new Guid("336748a5-854e-4220-8131-c54e10b2b2e8"), Description = "Soups", Cost = 2354, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 47, DateTimeKind.Utc) },
                new { Id = 38, Guid = new Guid("45733ed5-a793-46ed-b85d-67cd5eacafcb"), Description = "Tomatoes", Cost = 8923, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 53, DateTimeKind.Utc) },
                new { Id = 39, Guid = new Guid("3f5a3b0b-4138-4a16-ba5a-d92ed1f6e822"), Description = "Veggies", Cost = 5045, CategoryId = 2, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 59, DateTimeKind.Utc) },
                new { Id = 40, Guid = new Guid("b72ee931-1cd9-45bf-8c27-5ec706d4715b"), Description = "Beer", Cost = 7736, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 70, DateTimeKind.Utc) },
                new { Id = 41, Guid = new Guid("bfa3a519-3f1a-4f7b-b75c-b9991edfd62a"), Description = "Cider", Cost = 3857, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 76, DateTimeKind.Utc) },
                new { Id = 42, Guid = new Guid("181deee0-1572-4644-9838-b8977ef1ca28"), Description = "Cocktails", Cost = 427, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 82, DateTimeKind.Utc) },
                new { Id = 43, Guid = new Guid("5cce6d37-d6b8-4f42-877b-368d8528717f"), Description = "Hard soda", Cost = 1773, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 88, DateTimeKind.Utc) },
                new { Id = 44, Guid = new Guid("f343d76b-139a-4e5b-87d8-fd633fc05126"), Description = "Wine", Cost = 3118, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 94, DateTimeKind.Utc) },
                new { Id = 45, Guid = new Guid("591bdfc8-bdac-45b0-948a-6853e58f44ee"), Description = "Barley", Cost = 4464, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 101, DateTimeKind.Utc) },
                new { Id = 46, Guid = new Guid("b653981f-e59c-4220-a9a8-ad9546a29281"), Description = "Mixed drinks", Cost = 1034, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 108, DateTimeKind.Utc) },
                new { Id = 47, Guid = new Guid("f4d1fe9d-1cda-4e18-9ac1-fbf10648cae2"), Description = "Coffee", Cost = 2379, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 114, DateTimeKind.Utc) },
                new { Id = 48, Guid = new Guid("942f3df6-991e-44e4-9cf4-02aa664ca405"), Description = "Hot chocolate", Cost = 3724, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 120, DateTimeKind.Utc) },
                new { Id = 49, Guid = new Guid("d4128662-1e3a-4d2a-8e39-8da035b37e58"), Description = "Lemon tea", Cost = 295, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 127, DateTimeKind.Utc) },
                new { Id = 50, Guid = new Guid("947fc5a4-de11-4441-8305-913abfe54d4a"), Description = "Soft drinks", Cost = 6864, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 134, DateTimeKind.Utc) },
                new { Id = 51, Guid = new Guid("70e6a8db-b7d7-4127-97e9-275b73e4d214"), Description = "Milk", Cost = 3434, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 141, DateTimeKind.Utc) },
                new { Id = 52, Guid = new Guid("251d9082-3a9a-44b8-9fad-55cec34f7303"), Description = "Water", Cost = 4, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 148, DateTimeKind.Utc) },
                new { Id = 53, Guid = new Guid("5c8be2ca-3d9a-427b-bbf2-ae8bcdf9becf"), Description = "Juice drinks", Cost = 6573, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 164, DateTimeKind.Utc) },
                new { Id = 54, Guid = new Guid("45d10c03-233d-4f25-b48c-69c3d5f9e992"), Description = "Green tea", Cost = 162, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 171, DateTimeKind.Utc) },
                new { Id = 55, Guid = new Guid("e99512f4-c8ae-439a-a192-c4e1879908dc"), Description = "Beer cocktail", Cost = 6731, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 178, DateTimeKind.Utc) },
                new { Id = 56, Guid = new Guid("d6d21376-46d3-49db-b3ab-78b797a0b9db"), Description = "Coconut water", Cost = 8076, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 184, DateTimeKind.Utc) },
                new { Id = 57, Guid = new Guid("ac1b12b9-82ef-4872-b998-d97b75fd112a"), Description = "Orange juice", Cost = 4646, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 191, DateTimeKind.Utc) },
                new { Id = 58, Guid = new Guid("86bc180e-bb93-442a-aae1-f0164aaef3de"), Description = "Apple juice", Cost = 1216, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 198, DateTimeKind.Utc) },
                new { Id = 59, Guid = new Guid("82b9bb34-8710-4004-91a6-a83fa1abaa0e"), Description = "Almond milk", Cost = 7786, CategoryId = 3, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 205, DateTimeKind.Utc) },
                new { Id = 60, Guid = new Guid("05792899-b79d-47b5-b636-c9faead561e9"), Description = "Lenovo IdeaPad 120s", Cost = 5701, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 218, DateTimeKind.Utc) },
                new { Id = 61, Guid = new Guid("6bff6083-7a0a-48ea-a36b-dcb4d929ae6f"), Description = "Asus Vivobook E403NA", Cost = 7046, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 225, DateTimeKind.Utc) },
                new { Id = 62, Guid = new Guid("c39fbea2-2740-4100-98b4-fd572292fc95"), Description = "Acer Aspire E15-575", Cost = 8840, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 232, DateTimeKind.Utc) },
                new { Id = 63, Guid = new Guid("26233aed-f7c2-4618-ad71-aab97b9ce47c"), Description = "Lenovo ThinkPad T440 (refurb)", Cost = 5410, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 239, DateTimeKind.Utc) },
                new { Id = 64, Guid = new Guid("fbc2b896-c094-4233-9d84-65f81bb3b22c"), Description = "Lenovo ThinkPad T440s (refurb)", Cost = 1981, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 246, DateTimeKind.Utc) },
                new { Id = 65, Guid = new Guid("c7816a94-e3d9-48f5-a2ae-e7eee34600ad"), Description = "Dell Inspiron 13 i5379", Cost = 8550, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 253, DateTimeKind.Utc) },
                new { Id = 66, Guid = new Guid("cd01b788-2093-45b4-a45a-a490981412f0"), Description = "Asus Vivobook F510UA", Cost = 5120, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 261, DateTimeKind.Utc) },
                new { Id = 67, Guid = new Guid("805d5b73-9ce5-407d-906f-de718d73d8e2"), Description = "Acer Aspire E5-576G", Cost = 6914, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 268, DateTimeKind.Utc) },
                new { Id = 68, Guid = new Guid("5fef81fb-690f-4247-aaab-af9d8e18ecc7"), Description = "Lenovo ThinkPad E470*", Cost = 8707, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 276, DateTimeKind.Utc) },
                new { Id = 69, Guid = new Guid("d2f4b90b-bdc1-4f67-8f54-06dfe8098146"), Description = "Asus Zenbook UX330UA", Cost = 5278, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 283, DateTimeKind.Utc) },
                new { Id = 70, Guid = new Guid("97873410-bdec-4cdb-a69a-031bb4504b2e"), Description = "Lenovo ThinkPad 13 *", Cost = 1848, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 291, DateTimeKind.Utc) },
                new { Id = 71, Guid = new Guid("697130df-3b1f-4044-9a9f-1f8d214492d4"), Description = "Dell Latitude 14 3480*", Cost = 3641, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 298, DateTimeKind.Utc) },
                new { Id = 72, Guid = new Guid("3a604c2f-6cbe-4b8e-989b-221751d768d7"), Description = "HP Envy 13", Cost = 5435, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 307, DateTimeKind.Utc) },
                new { Id = 73, Guid = new Guid("f0db7254-3e69-4acf-974f-f01a7b41e35f"), Description = "Apple Macbook Air 13", Cost = 7229, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 315, DateTimeKind.Utc) },
                new { Id = 74, Guid = new Guid("ce44ebc3-9842-4e6a-b861-f87cbdcf62e1"), Description = "Dell XPS 13 9360", Cost = 4248, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 324, DateTimeKind.Utc) },
                new { Id = 75, Guid = new Guid("28af3f06-391e-4e49-98e1-a82b924796ea"), Description = "Lenovo ThinkPad T470*", Cost = 6042, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 332, DateTimeKind.Utc) },
                new { Id = 76, Guid = new Guid("c4e57fea-416b-4340-b671-72a03bd7d0fd"), Description = "Lenovo ThinkPad T570*", Cost = 3060, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 341, DateTimeKind.Utc) },
                new { Id = 77, Guid = new Guid("cde151c5-751b-40bb-aaa4-17e21a4fd41a"), Description = "Lenovo ThinkPad X270*", Cost = 4854, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 349, DateTimeKind.Utc) },
                new { Id = 78, Guid = new Guid("78bb36d5-23d6-461b-843d-002c22d3205a"), Description = "Dell Latitude 14 3490*", Cost = 1873, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 358, DateTimeKind.Utc) },
                new { Id = 79, Guid = new Guid("d9a2ded7-8ee2-4ed6-9df9-1ca84a07e3a6"), Description = "Asus Zenbook UX430UA", Cost = 3666, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 366, DateTimeKind.Utc) },
                new { Id = 80, Guid = new Guid("84dad537-2eaa-4985-9584-afc4d6585aa0"), Description = "Lenovo ThinkPad T470p*", Cost = 5909, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 375, DateTimeKind.Utc) },
                new { Id = 81, Guid = new Guid("6de660ab-cf91-46f4-9f44-cb1fe2aa2145"), Description = "Dell Latitude 15 E5580*", Cost = 2927, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 385, DateTimeKind.Utc) },
                new { Id = 82, Guid = new Guid("03626b53-8276-4eb1-b444-a5c6050af13c"), Description = "Dell XPS 13 9370 Dev. Edition", Cost = 5170, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 395, DateTimeKind.Utc) },
                new { Id = 83, Guid = new Guid("e2d0c642-e8da-4661-9f59-68543454d55a"), Description = "Lenovo ThinkPad T470s*", Cost = 7412, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 406, DateTimeKind.Utc) },
                new { Id = 84, Guid = new Guid("712392a2-c9d4-4812-b9d3-2001447bd371"), Description = "Dell XPS 15 9560 (i5 refurb)", Cost = 4879, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 417, DateTimeKind.Utc) },
                new { Id = 85, Guid = new Guid("28741563-9c8b-48f0-bb24-925e1d7208d6"), Description = "HP Spectre 13", Cost = 2346, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 428, DateTimeKind.Utc) },
                new { Id = 86, Guid = new Guid("6302beb0-7018-4042-ad4b-d2ff90aba63f"), Description = "Dell XPS 13 9370", Cost = 9812, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 438, DateTimeKind.Utc) },
                new { Id = 87, Guid = new Guid("488748da-4590-490f-82e2-1d75205cf5dc"), Description = "Lenovo ThinkPad X1 Carbon", Cost = 2055, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 449, DateTimeKind.Utc) },
                new { Id = 88, Guid = new Guid("477200b0-1cb9-4475-8c26-814a2e2979ac"), Description = "Dell Latitude 15 E5590*", Cost = 9521, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 460, DateTimeKind.Utc) },
                new { Id = 89, Guid = new Guid("253195bb-359f-4cf3-aaad-e3d5f51301f7"), Description = "HP Elitebook 1040 G4", Cost = 6988, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 470, DateTimeKind.Utc) },
                new { Id = 90, Guid = new Guid("fbfe19c5-e956-48eb-949c-cd89f5cb408b"), Description = "Dell XPS 15 9560 (i5)", Cost = 9231, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 481, DateTimeKind.Utc) },
                new { Id = 91, Guid = new Guid("9407c259-2460-46d3-b0f1-8c6d8fd9bc53"), Description = "Dell XPS 15 9560 (i7 refurb)", Cost = 6249, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 490, DateTimeKind.Utc) },
                new { Id = 92, Guid = new Guid("75e5c7b0-42e7-458e-b537-48a04fac8b42"), Description = "Dell Latitude 14 E7490", Cost = 8492, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 500, DateTimeKind.Utc) },
                new { Id = 93, Guid = new Guid("419e10b3-f630-4ce5-958d-043660b044c9"), Description = "Asus Zenbook UX550VE", Cost = 735, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 510, DateTimeKind.Utc) },
                new { Id = 94, Guid = new Guid("50f3123a-dcfa-4754-83ab-01a0e50fc620"), Description = "Apple Macbook Pro 13", Cost = 2977, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 520, DateTimeKind.Utc) },
                new { Id = 95, Guid = new Guid("fc68d3cc-e700-479b-bc41-77a26fde86b9"), Description = "Asus Zenbook UX490UA", Cost = 5220, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 530, DateTimeKind.Utc) },
                new { Id = 96, Guid = new Guid("1e239b9e-f73e-40e6-801d-e70c2a36e8b3"), Description = "Dell XPS 15 9560 (i7)", Cost = 2687, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 541, DateTimeKind.Utc) },
                new { Id = 97, Guid = new Guid("bdbd32a6-6907-4941-be72-c84077fc7abc"), Description = "Apple Macbook Pro 15 w/ bar", Cost = 4929, CategoryId = 4, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 551, DateTimeKind.Utc) },
                new { Id = 98, Guid = new Guid("feab0666-146e-4bd3-89b1-481eb61eac43"), Description = "Alldocube iPlay 30", Cost = 8965, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 569, DateTimeKind.Utc) },
                new { Id = 99, Guid = new Guid("a1ccf137-22a2-4c15-b550-ac8acbebc2fb"), Description = "Amazon Fire HD 10", Cost = 1208, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 579, DateTimeKind.Utc) },
                new { Id = 100, Guid = new Guid("8fe455c0-f186-4c51-a204-535ab45f3f1b"), Description = "Chuwi SurPad", Cost = 3451, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 589, DateTimeKind.Utc) },
                new { Id = 101, Guid = new Guid("e79245c2-0ac9-4bbf-9e23-bd468d428a91"), Description = "Lenovo Smart Tab M10", Cost = 918, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 600, DateTimeKind.Utc) },
                new { Id = 102, Guid = new Guid("a67308f3-5f85-47a6-8f53-b72850443c31"), Description = "Lenovo Tab 11", Cost = 8384, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 611, DateTimeKind.Utc) },
                new { Id = 103, Guid = new Guid("3f76aeb7-9887-4701-bf84-3df4ff66926a"), Description = "Lenovo Tab 11 Pro", Cost = 5851, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 622, DateTimeKind.Utc) },
                new { Id = 104, Guid = new Guid("45d15ac3-bf13-4fe4-972f-ebc7f27b97bc"), Description = "Lenovo Tab M10 Plus FHD", Cost = 8093, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 632, DateTimeKind.Utc) },
                new { Id = 105, Guid = new Guid("ebfb0c43-bdda-4b17-adc0-7847eb44966b"), Description = "Google Assistant", Cost = 5560, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 642, DateTimeKind.Utc) },
                new { Id = 106, Guid = new Guid("04b864bb-c315-4a63-ae32-72de91a9d645"), Description = "Lenovo Smart Tab P10", Cost = 7802, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 654, DateTimeKind.Utc) },
                new { Id = 107, Guid = new Guid("13a86f56-63cc-4a66-8c43-5b830e31d80f"), Description = "Lenovo Tab M10", Cost = 494, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 665, DateTimeKind.Utc) },
                new { Id = 108, Guid = new Guid("00b5dff2-69da-4f95-84b2-ba9617e85df7"), Description = "Lenovo Yoga Smart Tab", Cost = 7960, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 677, DateTimeKind.Utc) },
                new { Id = 109, Guid = new Guid("5d3cc617-cddf-4710-9f9f-f86436515f42"), Description = "LG G Pad 5 10.1 FHD", Cost = 5427, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 688, DateTimeKind.Utc) },
                new { Id = 110, Guid = new Guid("cc2e2e30-05bd-4a92-b9b0-e2e254cc2488"), Description = "Onn 10", Cost = 2894, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 698, DateTimeKind.Utc) },
                new { Id = 111, Guid = new Guid("4765b29f-3975-45a5-9d6e-63368512b589"), Description = "Samsung Galaxy Tab A7", Cost = 361, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 709, DateTimeKind.Utc) },
                new { Id = 112, Guid = new Guid("c03cb901-d0cd-42fe-9c5e-4b6b6b58069c"), Description = "Samsung Galaxy Tab A 10.1", Cost = 3052, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 721, DateTimeKind.Utc) },
                new { Id = 113, Guid = new Guid("f2eb1fb8-b876-4a3b-9e56-c195942c2362"), Description = "Samsung Galaxy Tab A 10.5", Cost = 5743, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 734, DateTimeKind.Utc) },
                new { Id = 114, Guid = new Guid("3481ed43-ef09-43f2-8950-afad89dd50df"), Description = "Samsung Galaxy Tab S4 10.5", Cost = 3658, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 747, DateTimeKind.Utc) },
                new { Id = 115, Guid = new Guid("229bac45-4973-4156-b6d6-3adfaa52278a"), Description = "Samsung Galaxy Tab S5e", Cost = 6349, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 758, DateTimeKind.Utc) },
                new { Id = 116, Guid = new Guid("165de709-da7e-4952-99ca-295db89790eb"), Description = "Samsung Galaxy Tab S6", Cost = 3816, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 770, DateTimeKind.Utc) },
                new { Id = 117, Guid = new Guid("8adb2269-7c41-4ffb-8fa8-7d1ff6406182"), Description = "Samsung Galaxy Tab S6 Lite", Cost = 1732, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 782, DateTimeKind.Utc) },
                new { Id = 118, Guid = new Guid("70435883-678f-463c-ad2a-d427537559ce"), Description = "Samsung Galaxy Tab S7", Cost = 4422, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 795, DateTimeKind.Utc) },
                new { Id = 119, Guid = new Guid("f58aa98c-efb9-46a2-af7b-71f22bdf3f54"), Description = "Samsung Galaxy Tab S7+", Cost = 3235, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 812, DateTimeKind.Utc) },
                new { Id = 120, Guid = new Guid("2a32bbb0-bd5a-4dcb-9792-53f75a4a76a7"), Description = "Teclast M40", Cost = 1599, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 827, DateTimeKind.Utc) },
                new { Id = 121, Guid = new Guid("72124a05-09b2-4c79-937c-46db5c147840"), Description = "Teclast P20HD", Cost = 4738, CategoryId = 5, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 841, DateTimeKind.Utc) },
                new { Id = 122, Guid = new Guid("3100f340-0893-4c04-9980-7356fa7a8f2d"), Description = "Chuck Taylor", Cost = 5344, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 867, DateTimeKind.Utc) },
                new { Id = 123, Guid = new Guid("7353c5d2-470c-4c81-880b-66a6dc062f78"), Description = "Golf shoes", Cost = 8484, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 880, DateTimeKind.Utc) },
                new { Id = 124, Guid = new Guid("f7804ce0-c7d4-4b8e-8189-28458b645106"), Description = "Hiking boots", Cost = 6399, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 893, DateTimeKind.Utc) },
                new { Id = 125, Guid = new Guid("d0740658-c391-469c-8e3d-be79d77e04ec"), Description = "High-tops", Cost = 4315, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 907, DateTimeKind.Utc) },
                new { Id = 126, Guid = new Guid("3487569b-1b45-4d4a-9444-68b41e041cc6"), Description = "Running shoes", Cost = 7454, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 920, DateTimeKind.Utc) },
                new { Id = 127, Guid = new Guid("c2691aa4-dd20-4020-8d85-800725dae3cb"), Description = "Climbing shoes", Cost = 594, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 934, DateTimeKind.Utc) },
                new { Id = 128, Guid = new Guid("185e823f-8354-4a6b-91c1-42f07493aa95"), Description = "Soccer shoes", Cost = 3733, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 949, DateTimeKind.Utc) },
                new { Id = 129, Guid = new Guid("6e7fe03e-4e7c-4fb7-9861-f5fd2486a524"), Description = "Sneakers (U.S)/ Trainers (U.K)", Cost = 6873, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 962, DateTimeKind.Utc) },
                new { Id = 130, Guid = new Guid("89145bc7-6297-4664-b1b7-af4c2c554905"), Description = "Old skool", Cost = 4788, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 975, DateTimeKind.Utc) },
                new { Id = 131, Guid = new Guid("7ba99059-5556-4e5e-8c72-3f7183a7d008"), Description = "Basketball shoes", Cost = 2704, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 10, 988, DateTimeKind.Utc) },
                new { Id = 132, Guid = new Guid("6a516d9f-bba4-4757-8c09-07020ad19128"), Description = "Ice-skates", Cost = 1067, CategoryId = 6, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 4, DateTimeKind.Utc) },
                new { Id = 133, Guid = new Guid("67a31c19-ff23-4567-ae44-3f74bca67fa1"), Description = "Rolex", Cost = 3093, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 31, DateTimeKind.Utc) },
                new { Id = 134, Guid = new Guid("89014789-f71b-4257-85ba-912d98678228"), Description = "Patek Philippe", Cost = 6232, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 47, DateTimeKind.Utc) },
                new { Id = 135, Guid = new Guid("334d4496-3ae3-4d4b-8636-f8dc67854129"), Description = "Audemars Piguet", Cost = 4596, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 61, DateTimeKind.Utc) },
                new { Id = 136, Guid = new Guid("9075f0f5-1d67-4247-8ee6-fffb2d0de341"), Description = "A.Lange & S�hne", Cost = 7736, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 74, DateTimeKind.Utc) },
                new { Id = 137, Guid = new Guid("c887c8cf-0615-46d7-bfb6-0b749082172b"), Description = "Omega", Cost = 876, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 88, DateTimeKind.Utc) },
                new { Id = 138, Guid = new Guid("8f4d45ec-3eb3-4555-8417-bcc2ff02e2c9"), Description = "Blancpain", Cost = 4912, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 106, DateTimeKind.Utc) },
                new { Id = 139, Guid = new Guid("9eed3986-2695-4b3a-9158-acf6ecbe2abd"), Description = "IWC Schaffhausen", Cost = 2828, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 118, DateTimeKind.Utc) },
                new { Id = 140, Guid = new Guid("09434af8-9bf3-4faf-ac10-64642cf807db"), Description = "Jaeger-LeCoultre", Cost = 743, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 132, DateTimeKind.Utc) },
                new { Id = 141, Guid = new Guid("a7d3e46a-e62a-4a28-bafd-76389aabc4ac"), Description = "Chopard", Cost = 8658, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 145, DateTimeKind.Utc) },
                new { Id = 142, Guid = new Guid("b133b4ea-714b-4363-b91b-fcadf7f4e191"), Description = "Piaget", Cost = 6573, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 158, DateTimeKind.Utc) },
                new { Id = 143, Guid = new Guid("382c571a-b61d-4d13-b00c-0951168c4f1b"), Description = "Cartier", Cost = 4489, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 171, DateTimeKind.Utc) },
                new { Id = 144, Guid = new Guid("f3aa49df-fbc8-45bd-9616-801ae7c5a46e"), Description = "Vacheron Constantin", Cost = 2404, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 184, DateTimeKind.Utc) },
                new { Id = 145, Guid = new Guid("f49a5053-c23b-4e1a-b1fe-42282cb9c5ee"), Description = "Montblanc", Cost = 320, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 198, DateTimeKind.Utc) },
                new { Id = 146, Guid = new Guid("c6052919-36ee-40cd-b624-026bb095b17b"), Description = "Ulysse Nardin", Cost = 3459, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 211, DateTimeKind.Utc) },
                new { Id = 147, Guid = new Guid("d997ea88-12d7-46a6-ac85-a4b401a71de4"), Description = "Panerai", Cost = 1374, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 224, DateTimeKind.Utc) },
                new { Id = 148, Guid = new Guid("fe78427d-d2ef-4693-a9d5-f5b3ca676fef"), Description = "Girard-Perregaux", Cost = 4513, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 238, DateTimeKind.Utc) },
                new { Id = 149, Guid = new Guid("3e3475dd-a2a0-40b9-8792-ab053f213dcd"), Description = "Hublot", Cost = 7653, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 252, DateTimeKind.Utc) },
                new { Id = 150, Guid = new Guid("54e7c931-0e8e-4972-9c1c-ad888b87993b"), Description = "Bulgari", Cost = 5568, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 265, DateTimeKind.Utc) },
                new { Id = 151, Guid = new Guid("79d7f3dd-71ab-4b47-b733-009f26405b12"), Description = "NOMOS Glash�tte", Cost = 3484, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 278, DateTimeKind.Utc) },
                new { Id = 152, Guid = new Guid("37530a8d-bfd9-45d5-bab3-aa00e86dd4c7"), Description = "Vincero", Cost = 1399, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 291, DateTimeKind.Utc) },
                new { Id = 153, Guid = new Guid("e6a5dd4a-e832-472f-8d52-23b3b14f1e8a"), Description = "Breitling", Cost = 9314, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 304, DateTimeKind.Utc) },
                new { Id = 154, Guid = new Guid("0c8f4673-1bad-4eaa-b77e-bd346dc65797"), Description = "Bremont", Cost = 2902, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 321, DateTimeKind.Utc) },
                new { Id = 155, Guid = new Guid("aa6db029-f9f7-4d69-a685-74aa16c59b49"), Description = "TAG Heuer", Cost = 6490, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 336, DateTimeKind.Utc) },
                new { Id = 156, Guid = new Guid("eef6e48c-5d44-4192-b46e-715b50fe831f"), Description = "Baume & Mercier", Cost = 9629, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 350, DateTimeKind.Utc) },
                new { Id = 157, Guid = new Guid("6cd4c34e-856b-4361-a1d2-79c097bad2d3"), Description = "Rado", Cost = 7545, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 363, DateTimeKind.Utc) },
                new { Id = 158, Guid = new Guid("fdfdb337-5c67-4ed2-b101-6e38e4d70b57"), Description = "Maurice Lacroix", Cost = 685, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 377, DateTimeKind.Utc) },
                new { Id = 159, Guid = new Guid("7d45ab25-cb84-47ab-b6af-2082ef0f5668"), Description = "Roger Dubuis", Cost = 8600, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 391, DateTimeKind.Utc) },
                new { Id = 160, Guid = new Guid("d008dd15-85b2-41ab-a8c3-415f8c8eca7f"), Description = "F.P.Journe", Cost = 1740, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 404, DateTimeKind.Utc) },
                new { Id = 161, Guid = new Guid("757b5d0b-8aeb-467b-9158-e82eb05652f5"), Description = "Tiffany & Co.", Cost = 4879, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 418, DateTimeKind.Utc) },
                new { Id = 162, Guid = new Guid("52bc342c-42f1-49ab-867e-b12bf3eb248f"), Description = "Louis Vuitton", Cost = 2794, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 433, DateTimeKind.Utc) },
                new { Id = 163, Guid = new Guid("4f176611-b91d-4298-972e-29cf45a90298"), Description = "Bamford", Cost = 7728, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 478, DateTimeKind.Utc) },
                new { Id = 164, Guid = new Guid("1a3ec1f9-f24c-4d76-b7a3-6dfb42d57515"), Description = "Zenith", Cost = 2080, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 527, DateTimeKind.Utc) },
                new { Id = 165, Guid = new Guid("abc874b4-e1f4-4b7c-9398-c11cd9e3fd00"), Description = "Bell & Ross", Cost = 4032, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 549, DateTimeKind.Utc) },
                new { Id = 166, Guid = new Guid("7aae96bc-5971-44a1-8910-80ef7f927d07"), Description = "Arnold & Son", Cost = 2396, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 564, DateTimeKind.Utc) },
                new { Id = 167, Guid = new Guid("166fa5c6-0fb5-4a4b-a78f-f798ebce9fcd"), Description = "Tudor", Cost = 760, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 578, DateTimeKind.Utc) },
                new { Id = 168, Guid = new Guid("f4cd4981-dedf-4289-a8b8-6e00427100be"), Description = "Alpina", Cost = 3899, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 593, DateTimeKind.Utc) },
                new { Id = 169, Guid = new Guid("ecb4e31e-21aa-410c-896f-ee877eb8fe10"), Description = "Seiko", Cost = 2263, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 609, DateTimeKind.Utc) },
                new { Id = 170, Guid = new Guid("c26d0c02-5991-4729-8d0e-3f2a43ed2584"), Description = "Jaquet Droz", Cost = 5851, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 624, DateTimeKind.Utc) },
                new { Id = 171, Guid = new Guid("28582f01-a287-4b44-acf2-f2f8d54d7b28"), Description = "Laurent Ferrier", Cost = 8990, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 638, DateTimeKind.Utc) },
                new { Id = 172, Guid = new Guid("64b9149b-4484-4b40-a1c7-e267ac3bf474"), Description = "Hamilton", Cost = 7354, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 654, DateTimeKind.Utc) },
                new { Id = 173, Guid = new Guid("4d5c1ddb-b05b-46a6-95f0-60f77206271f"), Description = "Longines", Cost = 943, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 670, DateTimeKind.Utc) },
                new { Id = 174, Guid = new Guid("712ac0e4-bf7d-45c8-b7f8-4e4b643f708e"), Description = "Maurice de Mauriac", Cost = 9306, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 684, DateTimeKind.Utc) },
                new { Id = 175, Guid = new Guid("0e478a1e-b1d1-4697-aa1c-e57828ac7420"), Description = "Parmigiani Fleurier", Cost = 2894, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 700, DateTimeKind.Utc) },
                new { Id = 176, Guid = new Guid("656c22d5-14db-47de-a259-920dc3c835ce"), Description = "Gucci", Cost = 6034, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 715, DateTimeKind.Utc) },
                new { Id = 177, Guid = new Guid("ecf5ec6b-5672-4710-8a04-5580d0c7dd20"), Description = "Weiss", Cost = 4398, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 730, DateTimeKind.Utc) },
                new { Id = 178, Guid = new Guid("a04a4781-e88b-4a88-bc78-37b17ae335da"), Description = "Armani", Cost = 7985, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 745, DateTimeKind.Utc) },
                new { Id = 179, Guid = new Guid("3247613c-1288-44f3-8b75-d916a7a08f7a"), Description = "Tissot", Cost = 6349, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 761, DateTimeKind.Utc) },
                new { Id = 180, Guid = new Guid("98809039-141b-4460-b6bf-20998861053f"), Description = "Van Cleef & Arpels", Cost = 4713, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 776, DateTimeKind.Utc) },
                new { Id = 181, Guid = new Guid("63eec370-7b5d-44fe-a62f-307ca885ea05"), Description = "Junghans", Cost = 8301, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 791, DateTimeKind.Utc) },
                new { Id = 182, Guid = new Guid("9e7a1d56-bf4f-4622-afeb-9021315a5712"), Description = "Bulova", Cost = 6665, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 807, DateTimeKind.Utc) },
                new { Id = 183, Guid = new Guid("b97d1a39-ac02-4280-9e5d-98b0b6a0c538"), Description = "Bovet Fleurier", Cost = 5477, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 823, DateTimeKind.Utc) },
                new { Id = 184, Guid = new Guid("3da9c2b9-f7e1-4468-abf3-01c965f34482"), Description = "Oris", Cost = 9065, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 839, DateTimeKind.Utc) },
                new { Id = 185, Guid = new Guid("af46b2f0-f723-4b92-972b-adace504168a"), Description = "Armin Strom", Cost = 2654, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 855, DateTimeKind.Utc) },
                new { Id = 186, Guid = new Guid("6c302b95-fc83-493b-849f-d562d54f9609"), Description = "Ressence", Cost = 1018, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 871, DateTimeKind.Utc) },
                new { Id = 187, Guid = new Guid("70506c57-6490-40b5-a5ac-8c38ca23e0ec"), Description = "Carl F. Bucherer", Cost = 4605, CategoryId = 7, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 886, DateTimeKind.Utc) },
                new { Id = 188, Guid = new Guid("7c8e49b2-f90f-4db0-828a-53c1caa964bc"), Description = "Abyss AB-1266 Phi TC", Cost = 1333, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 917, DateTimeKind.Utc) },
                new { Id = 189, Guid = new Guid("b7fafb59-a0a0-42c7-ad96-efecf3c19224"), Description = "Acousticom 1060-HS", Cost = 4921, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 932, DateTimeKind.Utc) },
                new { Id = 190, Guid = new Guid("63a4c351-dfbb-4729-a2f9-6c5f55ce6a18"), Description = "Active Headsets DRE-1001", Cost = 8509, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 948, DateTimeKind.Utc) },
                new { Id = 191, Guid = new Guid("3f4eb178-fd4a-445f-96bc-b64130cf5563"), Description = "ADAM Audio SP-5", Cost = 6873, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 964, DateTimeKind.Utc) },
                new { Id = 192, Guid = new Guid("9db54224-58ba-41df-8cb3-edf583677473"), Description = "ADATA XPG Precog", Cost = 461, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 980, DateTimeKind.Utc) },
                new { Id = 193, Guid = new Guid("4d7cdd20-16c3-4d4e-ac29-827a0c0d6a13"), Description = "Aeroservey E520067", Cost = 4049, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 11, 996, DateTimeKind.Utc) },
                new { Id = 194, Guid = new Guid("6a511cd5-43f7-4ff8-9cfc-5b122a1efc96"), Description = "Aftershokz Titanium", Cost = 8608, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 13, DateTimeKind.Utc) },
                new { Id = 195, Guid = new Guid("7df4a98f-f251-4ed6-92bd-a62a46acf116"), Description = "AIAIAI TMA-2", Cost = 7420, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 30, DateTimeKind.Utc) },
                new { Id = 196, Guid = new Guid("b10053c8-eea3-45b5-a855-9d1fb7e1bb45"), Description = "Ailihen C8", Cost = 1009, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 46, DateTimeKind.Utc) },
                new { Id = 197, Guid = new Guid("075713ba-524c-4669-b5a7-4b50b37fca9c"), Description = "Aircom A3x", Cost = 9820, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 62, DateTimeKind.Utc) },
                new { Id = 198, Guid = new Guid("5604043a-c61c-4227-9863-9d99092e8bb3"), Description = "AKG K812", Cost = 8184, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 78, DateTimeKind.Utc) },
                new { Id = 199, Guid = new Guid("aa2e88f8-1a61-4f19-866b-42f246cde3a1"), Description = "Allen & Heath XD2-53", Cost = 1773, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 95, DateTimeKind.Utc) },
                new { Id = 200, Guid = new Guid("640a5c54-f714-4ec6-8fce-e1d8fa047bbc"), Description = "Alesis DRP100", Cost = 585, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 111, DateTimeKind.Utc) },
                new { Id = 201, Guid = new Guid("78202662-9357-409a-bef2-a887d65c3631"), Description = "Alphatec Beatbox i08", Cost = 4173, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 127, DateTimeKind.Utc) },
                new { Id = 202, Guid = new Guid("5fe11f29-09be-42c0-b03f-4403151735ff"), Description = "Amazon Echo Buds", Cost = 8209, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 145, DateTimeKind.Utc) },
                new { Id = 203, Guid = new Guid("32ccad01-507a-4d07-822a-07429e7dc1a5"), Description = "American Audio HP 550", Cost = 7021, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 162, DateTimeKind.Utc) },
                new { Id = 204, Guid = new Guid("b2d93d54-7237-47b1-8a10-3c919586a94b"), Description = "Amkette Trubeats Urban Bluetooth", Cost = 5834, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 179, DateTimeKind.Utc) },
                new { Id = 205, Guid = new Guid("c3e32c4b-5008-4b39-872d-3f3580713f8c"), Description = "Andrea Communications (Andrea Electronics) ANR-950", Cost = 9422, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 196, DateTimeKind.Utc) },
                new { Id = 206, Guid = new Guid("a8b14b45-4162-4b10-bf17-f7d9fe273e4a"), Description = "APCO Aviation Air Extreme PHD1", Cost = 8234, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 213, DateTimeKind.Utc) },
                new { Id = 207, Guid = new Guid("45470bda-c6d4-4574-80f3-71c004cb60b7"), Description = "Apex HP100", Cost = 7046, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 229, DateTimeKind.Utc) },
                new { Id = 208, Guid = new Guid("c29dac34-81a3-4dcd-a47f-aa0ba1d60a23"), Description = "Apple Air Pods", Cost = 635, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 246, DateTimeKind.Utc) },
                new { Id = 209, Guid = new Guid("1bc07d01-a6d8-4557-a412-101c121f00b7"), Description = "Arctic P253 BT", Cost = 9447, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 262, DateTimeKind.Utc) },
                new { Id = 210, Guid = new Guid("a7bb9a10-9940-4247-8edf-4357697758e6"), Description = "Astell & Kern AK T5p", Cost = 3484, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 280, DateTimeKind.Utc) },
                new { Id = 211, Guid = new Guid("1061fe35-3f07-418b-a0a1-a9a8549da4d8"), Description = "Astro A40 TR", Cost = 7520, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 297, DateTimeKind.Utc) },
                new { Id = 212, Guid = new Guid("3a508bd0-26ca-42b2-bbc1-fc86b655e20b"), Description = "Asus STRIX 7.1", Cost = 1557, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 316, DateTimeKind.Utc) },
                new { Id = 213, Guid = new Guid("e1d28d34-5aa6-4d0c-ac67-37c341e6d1d7"), Description = "Audeze LCD-4", Cost = 369, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 333, DateTimeKind.Utc) },
                new { Id = 214, Guid = new Guid("38b5bcdb-c31f-425c-a50c-2874fa17fa40"), Description = "AudioQuest NightOwl Carbon", Cost = 9181, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 351, DateTimeKind.Utc) },
                new { Id = 215, Guid = new Guid("2761b691-78a2-47dc-a080-0cb4c9967801"), Description = "Audio-Technica ATH-R70X", Cost = 3218, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 368, DateTimeKind.Utc) },
                new { Id = 216, Guid = new Guid("d1a34b77-ce43-46a4-ad84-1de26bf76fb7"), Description = "Ausdom AH2 Deep Bass", Cost = 7254, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 386, DateTimeKind.Utc) },
                new { Id = 217, Guid = new Guid("46217312-2c6a-4f85-b956-d8f49a43c650"), Description = "Austrian Audio Hi-X55", Cost = 6067, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 405, DateTimeKind.Utc) },
                new { Id = 218, Guid = new Guid("afd8c0a4-3127-4a6a-8644-5e1b7b713e36"), Description = "Avantone Pro MP-1", Cost = 5327, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 422, DateTimeKind.Utc) },
                new { Id = 219, Guid = new Guid("73dbf1b1-dbce-436f-ae8e-1d093a8c151f"), Description = "Avantree HT4186", Cost = 9364, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 440, DateTimeKind.Utc) },
                new { Id = 220, Guid = new Guid("33ddffca-d068-4a03-bf73-50edfe15d08f"), Description = "Awei Q38i", Cost = 3401, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 458, DateTimeKind.Utc) },
                new { Id = 221, Guid = new Guid("f867f1e7-10b8-43e2-8866-5aca61639db3"), Description = "Axel FX", Cost = 7437, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 477, DateTimeKind.Utc) },
                new { Id = 222, Guid = new Guid("b4a61662-8e0f-4e72-8035-134b986a37df"), Description = "Azusa E520067", Cost = 6698, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 496, DateTimeKind.Utc) },
                new { Id = 223, Guid = new Guid("210b171c-aac6-46d9-bdb2-f6414c0d64e1"), Description = "Bang & Olufsen Beoplay H9", Cost = 735, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 514, DateTimeKind.Utc) },
                new { Id = 224, Guid = new Guid("aa24ae77-209a-431d-b5be-3b7354371e13"), Description = "Beats Electronics Solo Pro", Cost = 9995, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 534, DateTimeKind.Utc) },
                new { Id = 225, Guid = new Guid("a6fa800a-8dd9-4498-b0ea-1cac3f6549f6"), Description = "Behringer HPS3000", Cost = 9256, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 552, DateTimeKind.Utc) },
                new { Id = 226, Guid = new Guid("3c031641-458a-49cb-b700-ef29f3facbd1"), Description = "Beyerdynamic T 1", Cost = 3293, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 570, DateTimeKind.Utc) },
                new { Id = 227, Guid = new Guid("5004b9ac-ea09-4103-8c67-756fb76230dd"), Description = "Blue Microphones ELLA", Cost = 7329, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 588, DateTimeKind.Utc) },
                new { Id = 228, Guid = new Guid("c3cbfbdc-9104-4b44-a3c7-61b340a41249"), Description = "Bluedio T-elf 2", Cost = 6590, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 606, DateTimeKind.Utc) },
                new { Id = 229, Guid = new Guid("8a285f2f-9c24-494c-9115-23f46aa83160"), Description = "Boombotix Master Headphones", Cost = 627, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 625, DateTimeKind.Utc) },
                new { Id = 230, Guid = new Guid("69af5ba2-2d63-457f-a243-0a23e6b558d1"), Description = "Boomphones Phantom Headphones", Cost = 4663, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 644, DateTimeKind.Utc) },
                new { Id = 231, Guid = new Guid("b526026f-8eeb-4ae5-a439-64c42a04f8b2"), Description = "Bose 700", Cost = 3924, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 662, DateTimeKind.Utc) },
                new { Id = 232, Guid = new Guid("c4a87ea6-dac6-46e3-88b6-49f229cf7cb4"), Description = "Bowers & Wilkins PX7", Cost = 8409, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 681, DateTimeKind.Utc) },
                new { Id = 233, Guid = new Guid("5e371f20-2696-4177-8641-03aaf038c30f"), Description = "Brainwavz Audio B400", Cost = 2446, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 700, DateTimeKind.Utc) },
                new { Id = 234, Guid = new Guid("1251467a-1011-4a06-9346-b101cda21b59"), Description = "Bush PHK-907", Cost = 1707, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 718, DateTimeKind.Utc) },
                new { Id = 235, Guid = new Guid("310ddd9b-2074-4a3e-909e-42e2e01ff749"), Description = "CAD Audio DH100", Cost = 5743, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 737, DateTimeKind.Utc) },
                new { Id = 236, Guid = new Guid("aba74fea-e824-48ce-8839-e0e211e25bbc"), Description = "Campfire Audio Andromeda", Cost = 5004, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 756, DateTimeKind.Utc) },
                new { Id = 237, Guid = new Guid("959609df-d2ae-46f2-af95-229a65360bc9"), Description = "CEntrance Cerene dB", Cost = 4265, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 775, DateTimeKind.Utc) },
                new { Id = 238, Guid = new Guid("f0683258-a59c-4578-88c4-5b80d846ed1f"), Description = "Clarity Aloft Classic Headset", Cost = 3526, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 794, DateTimeKind.Utc) },
                new { Id = 239, Guid = new Guid("a75afd58-e63d-4dcf-9161-275c99f6efde"), Description = "Clement Clark Communications Airlite 2200", Cost = 2786, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 813, DateTimeKind.Utc) },
                new { Id = 240, Guid = new Guid("d55811ea-5fd0-4eba-9f3e-6d93b87ce2fe"), Description = "Cobham N/A", Cost = 2047, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 833, DateTimeKind.Utc) },
                new { Id = 241, Guid = new Guid("340affa9-d320-4736-bf07-c27247a88230"), Description = "Cooler Master MH-751", Cost = 6532, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 853, DateTimeKind.Utc) },
                new { Id = 242, Guid = new Guid("ab81de2d-e530-401d-b894-b0f7db6b6b8f"), Description = "Corsair VOID PRO", Cost = 6241, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 873, DateTimeKind.Utc) },
                new { Id = 243, Guid = new Guid("9dd69712-80e5-4060-8b35-462e3415e072"), Description = "Cowin Audio E7 Pro", Cost = 5502, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 892, DateTimeKind.Utc) },
                new { Id = 244, Guid = new Guid("c2c66f91-49fd-4b19-978d-d17d5d5a804d"), Description = "Creative Aurvana Platinum", Cost = 4763, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 911, DateTimeKind.Utc) },
                new { Id = 245, Guid = new Guid("5bdc19e4-78e2-4270-96f4-f7e3ebd6ce69"), Description = "Culture Audio V1", Cost = 9248, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 931, DateTimeKind.Utc) },
                new { Id = 246, Guid = new Guid("a574136c-1437-49f5-b399-c950be94cd40"), Description = "David Clark Company H10-13.4", Cost = 3733, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 952, DateTimeKind.Utc) },
                new { Id = 247, Guid = new Guid("450903d0-9a87-4fdb-9b3e-62972ad651c6"), Description = "Decibullz Custom Molded Earplugs", Cost = 3443, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 972, DateTimeKind.Utc) },
                new { Id = 248, Guid = new Guid("7b4a1528-f9e6-4e14-8cd7-9e0284cb287e"), Description = "Definitive Technology Symphony 1", Cost = 8376, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 12, 995, DateTimeKind.Utc) },
                new { Id = 249, Guid = new Guid("130719d5-8cee-4e2a-8d1c-382696c346d8"), Description = "Denon AH-D9200", Cost = 3832, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 15, DateTimeKind.Utc) },
                new { Id = 250, Guid = new Guid("dfb74e54-2fd7-49c7-a570-89fea78f6ccc"), Description = "Dekoni Audio Blue", Cost = 8317, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 35, DateTimeKind.Utc) },
                new { Id = 251, Guid = new Guid("103c43f3-bb31-4dbf-99c1-abcadd43e03e"), Description = "Dexibell HF7", Cost = 2803, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 56, DateTimeKind.Utc) },
                new { Id = 252, Guid = new Guid("40ebfda5-c95c-497d-b183-8af41121781d"), Description = "Direct Sound EX29", Cost = 7287, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 76, DateTimeKind.Utc) },
                new { Id = 253, Guid = new Guid("7b525b5d-b9ae-4e7e-8c3c-04c6e06bfd26"), Description = "DITA Dream XLS", Cost = 1773, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 96, DateTimeKind.Utc) },
                new { Id = 254, Guid = new Guid("d81522a0-8037-4917-b101-e9747c354177"), Description = "Doppler Labs Here One Wireless Smart Earbuds", Cost = 1482, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 116, DateTimeKind.Utc) },
                new { Id = 255, Guid = new Guid("b018c315-4579-4085-821d-9fda279c1c07"), Description = "Echobox Audio TI-22BT", Cost = 5967, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 136, DateTimeKind.Utc) },
                new { Id = 256, Guid = new Guid("7540bd92-1872-4f9c-9391-bdc5e6139c4d"), Description = "Edifier W828NB", Cost = 452, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 157, DateTimeKind.Utc) },
                new { Id = 257, Guid = new Guid("45598af7-ee77-45ac-998d-d7123f11a544"), Description = "Etymotic Research ER4", Cost = 4937, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 177, DateTimeKind.Utc) },
                new { Id = 258, Guid = new Guid("f94efc91-7aa2-40ba-8256-e3a181d414b5"), Description = "Factem AVPBT01", Cost = 4646, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 197, DateTimeKind.Utc) },
                new { Id = 259, Guid = new Guid("8336d85a-0a09-41b7-9454-233ce3811331"), Description = "Faro G2 ANR", Cost = 3907, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 217, DateTimeKind.Utc) },
                new { Id = 260, Guid = new Guid("bf7edf6a-368d-4faa-a879-539315d4335c"), Description = "Ferrari By Logic3 T350", Cost = 3617, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 238, DateTimeKind.Utc) },
                new { Id = 261, Guid = new Guid("cb9e55ae-3075-430f-9c00-f5c9d35b1f8a"), Description = "Fender PureSonic Premium", Cost = 8101, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 258, DateTimeKind.Utc) },
                new { Id = 262, Guid = new Guid("4b21b7ac-7595-4452-8581-e9de523ff295"), Description = "FIIL Canviis", Cost = 7810, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 280, DateTimeKind.Utc) },
                new { Id = 263, Guid = new Guid("66a6587b-9994-4814-b32c-c3887b65d223"), Description = "FiiO F9", Cost = 2745, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 301, DateTimeKind.Utc) },
                new { Id = 264, Guid = new Guid("f3261042-342c-46bf-91c8-5bbb0e6b1be1"), Description = "Final E4000", Cost = 2454, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 322, DateTimeKind.Utc) },
                new { Id = 265, Guid = new Guid("dda583b0-73f1-4661-a438-47a5f2e8d89a"), Description = "Firacore F10 5.0", Cost = 2163, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 343, DateTimeKind.Utc) },
                new { Id = 266, Guid = new Guid("a0cdeff1-b240-4025-bbbb-87e7c8cfc824"), Description = "Flightcom 4DLX", Cost = 1873, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 364, DateTimeKind.Utc) },
                new { Id = 267, Guid = new Guid("352779c8-de18-4794-a884-e0d5531eba21"), Description = "Floyd Rose 3D Stereo Fabric", Cost = 1582, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 386, DateTimeKind.Utc) },
                new { Id = 268, Guid = new Guid("034aaad7-e607-41d6-889c-9f671604920f"), Description = "Focal Utopia", Cost = 1740, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 409, DateTimeKind.Utc) },
                new { Id = 269, Guid = new Guid("36c30dff-7bc9-4bd6-b3d1-65f6abb95394"), Description = "Focusrite HP60 MKIII", Cost = 1898, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 434, DateTimeKind.Utc) },
                new { Id = 270, Guid = new Guid("6f7a24e4-e3fe-4889-b0a7-24c36391bb7f"), Description = "Fostex RPmk3", Cost = 7728, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 459, DateTimeKind.Utc) },
                new { Id = 271, Guid = new Guid("d8c086af-24dd-40d8-9cdb-51a9bb85683e"), Description = "G.Skill RIPJAWS SV710", Cost = 3110, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 482, DateTimeKind.Utc) },
                new { Id = 272, Guid = new Guid("33ed5b36-7e50-4ec0-8e97-fb8df89e4d8b"), Description = "Gentex Gencom III", Cost = 8492, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 508, DateTimeKind.Utc) },
                new { Id = 273, Guid = new Guid("2a02c4e3-5c75-45a4-a042-3646f8410d32"), Description = "Gibson & Barnes GB-2000 ANR", Cost = 4323, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 533, DateTimeKind.Utc) },
                new { Id = 274, Guid = new Guid("2ca2848c-7af9-44f3-bf3b-edf90918132c"), Description = "Gold Awin NC", Cost = 602, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 559, DateTimeKind.Utc) },
                new { Id = 275, Guid = new Guid("72a7afab-4f69-4ea8-9ec3-9cabe897448e"), Description = "Google Pixel Buds", Cost = 760, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 582, DateTimeKind.Utc) },
                new { Id = 276, Guid = new Guid("277c7490-40c4-4f7c-94c0-6b35b82606f4"), Description = "Grado Labs SR325e", Cost = 6141, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 607, DateTimeKind.Utc) },
                new { Id = 277, Guid = new Guid("bc37bbfa-87c6-411c-bb84-65846b8c7a3e"), Description = "GranVela A8", Cost = 6748, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 633, DateTimeKind.Utc) },
                new { Id = 278, Guid = new Guid("67df2643-ca9d-4510-9bdd-5b5327b95fb4"), Description = "Gripped Fitness Audio Rose Gold V.2", Cost = 2130, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 656, DateTimeKind.Utc) },
                new { Id = 279, Guid = new Guid("d34c88f9-2681-486d-ac0f-3d7aa305d129"), Description = "Happy Plugs Air 1", Cost = 7512, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 679, DateTimeKind.Utc) },
                new { Id = 280, Guid = new Guid("895d3bba-3c51-4631-b4f2-7c2d6a509996"), Description = "Harman Kardon Soho Wireless", Cost = 8118, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 706, DateTimeKind.Utc) },
                new { Id = 281, Guid = new Guid("2b8ee4a3-f0ff-4e0b-aaff-677af420377f"), Description = "HeadSound H5", Cost = 3501, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 728, DateTimeKind.Utc) },
                new { Id = 282, Guid = new Guid("155331d8-0a00-4236-9982-ffaee3e313b1"), Description = "Hear Technologies Future Sonics Spectrum Series G10", Cost = 8434, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 751, DateTimeKind.Utc) },
                new { Id = 283, Guid = new Guid("353c865a-4847-451a-affe-83a6a8c81b22"), Description = "HEDD Heddphones", Cost = 8591, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 773, DateTimeKind.Utc) },
                new { Id = 284, Guid = new Guid("2ff57387-2d83-4c4e-ae2f-5b4d23d69d49"), Description = "Heil Sound Pro Set 3", Cost = 3526, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 796, DateTimeKind.Utc) },
                new { Id = 285, Guid = new Guid("f407b68c-9f96-4b3a-8157-b26321bbb195"), Description = "Hercules HDP DJ M 40.1", Cost = 3683, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 819, DateTimeKind.Utc) },
                new { Id = 286, Guid = new Guid("d4efd820-780c-452c-a7d0-d7a607d5fbe8"), Description = "HiFiMan HE1000 V2", Cost = 8616, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 841, DateTimeKind.Utc) },
                new { Id = 287, Guid = new Guid("f0e56d36-6c83-47be-9fee-57aa2fb4ca11"), Description = "Holmberg HD-10-E", Cost = 3551, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 863, DateTimeKind.Utc) },
                new { Id = 288, Guid = new Guid("cf04ff39-1e46-4a92-babe-b5cb919bb6a9"), Description = "Hosa Technology HDS-100", Cost = 8932, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 886, DateTimeKind.Utc) },
                new { Id = 289, Guid = new Guid("b73b735b-dfb2-4a7c-becb-593342ef67ab"), Description = "House Of Marley Exodus", Cost = 3866, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 909, DateTimeKind.Utc) },
                new { Id = 290, Guid = new Guid("3be48de4-d287-4a97-a7d4-710bc005ac46"), Description = "HyperX Cloud Alpha S", Cost = 4024, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 932, DateTimeKind.Utc) },
                new { Id = 291, Guid = new Guid("e8a56068-45c6-4449-8886-feba6e278448"), Description = "iBall Earwear Rock", Cost = 8957, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 954, DateTimeKind.Utc) },
                new { Id = 292, Guid = new Guid("a61dba5a-ea74-41a4-92fa-11c5e40da7c5"), Description = "Icaro Comunica Electronics 3M X5", Cost = 9115, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 13, 977, DateTimeKind.Utc) },
                new { Id = 293, Guid = new Guid("180529c6-d0b6-40cf-ad82-1998670a7c6a"), Description = "IdeaUSA V200 ANC", Cost = 9273, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 1, DateTimeKind.Utc) },
                new { Id = 294, Guid = new Guid("0805c443-ed4d-470b-8655-2bcf102f1eee"), Description = "iFrogz Impulse", Cost = 402, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 24, DateTimeKind.Utc) },
                new { Id = 295, Guid = new Guid("2e3f1a25-f200-4c75-9e79-22818a9f90c4"), Description = "Imtradex Aircraft Control", Cost = 560, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 47, DateTimeKind.Utc) },
                new { Id = 296, Guid = new Guid("825e3d49-2693-4a2e-b0d4-7ffc84fc2b27"), Description = "IT7 Audio iT7xr", Cost = 718, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 70, DateTimeKind.Utc) },
                new { Id = 297, Guid = new Guid("261eeddf-fa6a-4705-a4a6-7b99e012dbd6"), Description = "Jabra Evolve 75", Cost = 1324, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 95, DateTimeKind.Utc) },
                new { Id = 298, Guid = new Guid("4354a9b4-28d9-40b0-bfd7-d393cd701374"), Description = "Jaybird Vista", Cost = 6706, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 119, DateTimeKind.Utc) },
                new { Id = 299, Guid = new Guid("f523fb24-98f1-4c4e-a28a-09caeaae7401"), Description = "Jays q-SEVEN", Cost = 6864, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 142, DateTimeKind.Utc) },
                new { Id = 300, Guid = new Guid("a871ef5e-b60a-4019-98d2-f81bfc065ca0"), Description = "JH Audio Layla", Cost = 2246, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 166, DateTimeKind.Utc) },
                new { Id = 301, Guid = new Guid("ccd5935d-8f24-4926-959e-af934ff3ccea"), Description = "JLab Studio SNC", Cost = 2404, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 189, DateTimeKind.Utc) },
                new { Id = 302, Guid = new Guid("1b46eff5-f909-48f2-901a-24a0154cdec1"), Description = "JVC Kenwood HA-XP50BT", Cost = 2562, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 213, DateTimeKind.Utc) },
                new { Id = 303, Guid = new Guid("e8091a33-b883-4965-8e0b-799386acba37"), Description = "KEF Space One", Cost = 7943, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 237, DateTimeKind.Utc) },
                new { Id = 304, Guid = new Guid("5c329738-e10b-401e-bcc0-90ae586185af"), Description = "Klipsch X20i", Cost = 3326, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 260, DateTimeKind.Utc) },
                new { Id = 305, Guid = new Guid("bca3aca6-2329-4a58-bf45-1990b0b96b2e"), Description = "Korg NC-Q1", Cost = 3484, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 288, DateTimeKind.Utc) },
                new { Id = 306, Guid = new Guid("1dcf8509-173e-4de0-9a59-476b5683af00"), Description = "Koss ESP950", Cost = 9762, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 311, DateTimeKind.Utc) },
                new { Id = 307, Guid = new Guid("12b121cd-91be-4379-b6ba-7ddc5ffbecd7"), Description = "KRK KNS 8400", Cost = 9920, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 334, DateTimeKind.Utc) },
                new { Id = 308, Guid = new Guid("68cbe2ab-f1ae-4f76-9e1e-8fbee9f6af4b"), Description = "Kygo Life Xenon", Cost = 5302, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 358, DateTimeKind.Utc) },
                new { Id = 309, Guid = new Guid("3bfbd16d-c504-46e6-a88b-615a4aef1d5c"), Description = "LB-Acoustics Mysphere 3", Cost = 5460, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 381, DateTimeKind.Utc) },
                new { Id = 310, Guid = new Guid("2b30ad6f-c1e8-496f-836c-c640fca86cba"), Description = "Lightspeed Zulu 3", Cost = 843, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 405, DateTimeKind.Utc) },
                new { Id = 311, Guid = new Guid("87070fd9-d229-4ab1-89e0-0d196da5087c"), Description = "Listen Technologies LA-454", Cost = 1001, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 429, DateTimeKind.Utc) },
                new { Id = 312, Guid = new Guid("fe78de0e-d88b-479b-a056-af490b17767a"), Description = "Livv Headphones LIVV Headphones", Cost = 6382, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 453, DateTimeKind.Utc) },
                new { Id = 313, Guid = new Guid("13721582-f917-4f94-a747-5ac73add5758"), Description = "LG Tone Platinum+", Cost = 6540, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 476, DateTimeKind.Utc) },
                new { Id = 314, Guid = new Guid("2c9994c3-6356-42fa-87b4-7b474d08c0eb"), Description = "Logitech Pro X (LogitechG)", Cost = 1923, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 500, DateTimeKind.Utc) },
                new { Id = 315, Guid = new Guid("5040c37d-f857-4919-a55c-df4bac6f78ad"), Description = "M-Audio HDH50", Cost = 2529, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 524, DateTimeKind.Utc) },
                new { Id = 316, Guid = new Guid("2f8d427e-1ecd-49db-ac76-2d364d2c0ef4"), Description = "Mackie MC-250", Cost = 2687, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 549, DateTimeKind.Utc) },
                new { Id = 317, Guid = new Guid("01ac4650-30cd-45cf-8c37-5000d87a01b9"), Description = "Marshall Amplification Monitor II", Cost = 3293, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 573, DateTimeKind.Utc) },
                new { Id = 318, Guid = new Guid("ab8063ee-e0b6-40e6-a1dd-4b172a5469a2"), Description = "Master & Dynamic MH40", Cost = 8674, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 598, DateTimeKind.Utc) },
                new { Id = 319, Guid = new Guid("23143a91-f376-4113-a3ef-0883df7ea2e5"), Description = "McIntosh MHP1000", Cost = 9281, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 621, DateTimeKind.Utc) },
                new { Id = 320, Guid = new Guid("15e3c105-56a0-40fa-aa42-1a81726f52ed"), Description = "MEE Audio Matrix Cinema", Cost = 9438, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 645, DateTimeKind.Utc) },
                new { Id = 321, Guid = new Guid("9391eee3-98e6-4906-8031-e090eb054cea"), Description = "Meizu EP-51", Cost = 4821, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 669, DateTimeKind.Utc) },
                new { Id = 322, Guid = new Guid("e1f83cb9-43aa-4ee6-89f7-97c5f173a6f1"), Description = "Metrophones Studio Kans", Cost = 5427, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 694, DateTimeKind.Utc) },
                new { Id = 323, Guid = new Guid("e9193ab0-0b1e-42d2-a774-434c8996e8ab"), Description = "Meze Audio Rai Penta", Cost = 6034, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 719, DateTimeKind.Utc) },
                new { Id = 324, Guid = new Guid("73a1351a-3b1b-4b44-9f44-c0a1a3c79ffa"), Description = "Micro Avionics ANR GA", Cost = 6640, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 744, DateTimeKind.Utc) },
                new { Id = 325, Guid = new Guid("1993b674-62c4-49e8-b259-49c92d7e7648"), Description = "Microsoft Xbox One Stereo", Cost = 2022, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 768, DateTimeKind.Utc) },
                new { Id = 326, Guid = new Guid("3573c313-9736-4cff-af88-4e954646a4d1"), Description = "Miktek DH80", Cost = 7404, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 792, DateTimeKind.Utc) },
                new { Id = 327, Guid = new Guid("f31b4c03-ddad-43af-a1e5-da47493d5faf"), Description = "Mixars MXH-22", Cost = 8010, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 818, DateTimeKind.Utc) },
                new { Id = 328, Guid = new Guid("2571bfa0-acaf-421a-aa54-6bfe27ef5518"), Description = "Monoprice M1570", Cost = 3841, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 843, DateTimeKind.Utc) },
                new { Id = 329, Guid = new Guid("d4bedb9f-833a-43a8-ac58-045d7300f702"), Description = "Monster Beats By Dre (formerly)", Cost = 4447, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 868, DateTimeKind.Utc) },
                new { Id = 330, Guid = new Guid("3e8e9174-9935-42ec-84d5-783b930479e4"), Description = "Mpow Flame Pro", Cost = 278, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 894, DateTimeKind.Utc) },
                new { Id = 331, Guid = new Guid("4ed789c8-186f-474f-8030-db2cc400eced"), Description = "MSA Supreme Pro", Cost = 885, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 920, DateTimeKind.Utc) },
                new { Id = 332, Guid = new Guid("f927e72b-d728-42bd-b170-0281e8223500"), Description = "Muxitek Muxitek Earbuds", Cost = 6715, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 945, DateTimeKind.Utc) },
                new { Id = 333, Guid = new Guid("93023852-fb31-4875-97f0-cb8cb26515b0"), Description = "Muzik LUX", Cost = 7321, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 970, DateTimeKind.Utc) },
                new { Id = 334, Guid = new Guid("ceae2639-451a-476f-8e18-b54d454bda95"), Description = "Mymanu CLIK", Cost = 7927, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 14, 995, DateTimeKind.Utc) },
                new { Id = 335, Guid = new Guid("11edd641-ee2b-4c85-a438-1cef798e7a7e"), Description = "Nady QH-200", Cost = 9505, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 21, DateTimeKind.Utc) },
                new { Id = 336, Guid = new Guid("fc7b28b5-3eee-4eba-b8b3-a20850b1bd54"), Description = "Nakamichi Edge", Cost = 112, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 47, DateTimeKind.Utc) },
                new { Id = 337, Guid = new Guid("25da0854-eea4-4dfd-b554-8ec0806cd540"), Description = "Neumann NHD-20", Cost = 5942, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 73, DateTimeKind.Utc) },
                new { Id = 338, Guid = new Guid("6b4b2a87-c82d-4ec9-814e-b8bcee06f989"), Description = "Nicepower AN-1000", Cost = 1773, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 99, DateTimeKind.Utc) },
                new { Id = 339, Guid = new Guid("4064c03b-2840-4165-9c5b-2d821edf1ccf"), Description = "Noble Falcon", Cost = 7603, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 124, DateTimeKind.Utc) },
                new { Id = 340, Guid = new Guid("4f29189b-e6ce-4f3e-9901-6790775316be"), Description = "Nuheara IBbuds2 MAX", Cost = 3434, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 150, DateTimeKind.Utc) },
                new { Id = 341, Guid = new Guid("8b0331ec-a093-443d-8e2f-ebdbbda66928"), Description = "Numark HF125", Cost = 4040, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 176, DateTimeKind.Utc) },
                new { Id = 342, Guid = new Guid("596bf89b-b759-41b9-9c35-71ac5a9625f5"), Description = "Nura Nuraphone", Cost = 9870, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 202, DateTimeKind.Utc) },
                new { Id = 343, Guid = new Guid("73d3209c-1319-491d-9bdd-6b3e39d0fd3a"), Description = "On-Stage BH4500", Cost = 5701, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 228, DateTimeKind.Utc) },
                new { Id = 344, Guid = new Guid("8d0bca72-2c01-422b-b05f-6e3b9b78bb5a"), Description = "OneOdio Pro-10", Cost = 1532, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 254, DateTimeKind.Utc) },
                new { Id = 345, Guid = new Guid("6a2ec477-2e4a-4ca2-a2bc-9efe4c4578fa"), Description = "Onkyo ES-FC300", Cost = 7362, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 279, DateTimeKind.Utc) },
                new { Id = 346, Guid = new Guid("aa3e2545-2ac0-4fa8-99b6-d66813480613"), Description = "OPPO PM-3", Cost = 3193, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 305, DateTimeKind.Utc) },
                new { Id = 347, Guid = new Guid("74cdabce-27ee-4029-b56f-a06e03106794"), Description = "Oxytronic iCan Wireless", Cost = 9023, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 332, DateTimeKind.Utc) },
                new { Id = 348, Guid = new Guid("1e8a46b6-cb53-4878-b12a-e3e31fdc519c"), Description = "Panasonic RP-HD10C", Cost = 4854, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 358, DateTimeKind.Utc) },
                new { Id = 349, Guid = new Guid("9d3d5fc0-3700-4bb4-809f-8e79ef7f076b"), Description = "Paraclete Aviation Life Support Aspida Carbon", Cost = 685, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 384, DateTimeKind.Utc) },
                new { Id = 350, Guid = new Guid("50be23e9-295e-41b6-8cb3-39eeebdd0167"), Description = "Parrot Jik 3", Cost = 6515, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 410, DateTimeKind.Utc) },
                new { Id = 351, Guid = new Guid("238c4ddf-5a77-4774-8ccb-4e954646a4d1"), Description = "PDP LVL50", Cost = 7570, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 437, DateTimeKind.Utc) },
                new { Id = 352, Guid = new Guid("f2006eb1-72bb-40f4-b916-a9246fa3488b"), Description = "Pendulumic STANCE S1", Cost = 8624, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 463, DateTimeKind.Utc) },
                new { Id = 353, Guid = new Guid("19b0e8b3-4b0f-49f5-a1a1-68bbda9f0538"), Description = "Periodic Audio \"Be\" Beryllium", Cost = 9679, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 490, DateTimeKind.Utc) },
                new { Id = 354, Guid = new Guid("39842bda-cefd-48f8-96db-dd69ad181ef2"), Description = "Phiaton MS530", Cost = 5510, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 518, DateTimeKind.Utc) },
                new { Id = 355, Guid = new Guid("e87b382f-3906-4af2-bfe6-9e481f91e5ca"), Description = "Philips Fidelio X2HR/00", Cost = 1790, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 545, DateTimeKind.Utc) },
                new { Id = 356, Guid = new Guid("64068850-2bad-41ed-874e-3eecf08e3662"), Description = "Photive BTX6", Cost = 3451, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 600, DateTimeKind.Utc) },
                new { Id = 357, Guid = new Guid("39e55277-3480-40a0-8882-32ed44e9ca24"), Description = "Pilot Communications PA-1779T", Cost = 5851, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 631, DateTimeKind.Utc) },
                new { Id = 358, Guid = new Guid("cc9e6a1a-9c9c-4550-9fc9-ea9f0052b063"), Description = "Pioneer SE-MASTER1", Cost = 2130, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 658, DateTimeKind.Utc) },
                new { Id = 359, Guid = new Guid("3ba06440-7c23-4724-baf9-77a6a7ba2bee"), Description = "Plantronics Voyager Legend", Cost = 3185, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 685, DateTimeKind.Utc) },
                new { Id = 360, Guid = new Guid("72938d01-c3bb-4943-b236-e3bb221922c9"), Description = "Polsen HPC-A30-MK2", Cost = 9015, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 711, DateTimeKind.Utc) },
                new { Id = 361, Guid = new Guid("1f1e7e11-13eb-4abf-a717-c796afdbfbc2"), Description = "PreSonus Eris HD10BT", Cost = 5294, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 740, DateTimeKind.Utc) },
                new { Id = 362, Guid = new Guid("ab7218b4-ac90-496b-89f6-5a8d777ec49d"), Description = "Pryma Pryma 01", Cost = 1574, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 767, DateTimeKind.Utc) },
                new { Id = 363, Guid = new Guid("e3200f32-6cdc-4f45-ab9f-8d0f35eff173"), Description = "PSB M4U 2", Cost = 2629, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 795, DateTimeKind.Utc) },
                new { Id = 364, Guid = new Guid("275dc2c7-4e57-465e-bd5d-774031e73849"), Description = "Pyle Pro PHPDJ1", Cost = 4132, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 823, DateTimeKind.Utc) },
                new { Id = 365, Guid = new Guid("ad090aa3-ad1c-4535-8a15-0f2cf4c661a7"), Description = "Rane Commercial RH-50", Cost = 5187, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 850, DateTimeKind.Utc) },
                new { Id = 366, Guid = new Guid("138dc50e-1518-406f-8061-2cae62bf725c"), Description = "Rapoo H6020", Cost = 6241, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 878, DateTimeKind.Utc) },
                new { Id = 367, Guid = new Guid("c111be47-5095-4378-89a4-c62ec968a6e5"), Description = "RayTalk PH-100A", Cost = 2521, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 905, DateTimeKind.Utc) },
                new { Id = 368, Guid = new Guid("b3789fd5-2a3b-4d7f-bba2-911bc9ea5414"), Description = "Razer Nari Ultimate", Cost = 3575, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 932, DateTimeKind.Utc) },
                new { Id = 369, Guid = new Guid("c1c72b67-9ec4-4735-87a2-4ddce1183e5b"), Description = "RCF Audio Iconica", Cost = 9854, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 960, DateTimeKind.Utc) },
                new { Id = 370, Guid = new Guid("733a0dc4-2693-48e4-abb3-c1d42081eaec"), Description = "Reloop SHP-8", Cost = 1358, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 15, 990, DateTimeKind.Utc) },
                new { Id = 371, Guid = new Guid("24c55383-fb4a-46e3-84da-ab3b9a2744a7"), Description = "Remote Audio HN-7506", Cost = 8608, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 21, DateTimeKind.Utc) },
                new { Id = 372, Guid = new Guid("4a79ea33-2abb-4413-a0db-c761bdd188f0"), Description = "Resident Audio R100", Cost = 560, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 50, DateTimeKind.Utc) },
                new { Id = 373, Guid = new Guid("cf6d7a26-cfb6-4579-bc36-66de751e8c7b"), Description = "RHA Technologies TrueConnect", Cost = 7287, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 81, DateTimeKind.Utc) },
                new { Id = 374, Guid = new Guid("a4621cf0-4ccb-48b5-b21c-007810bad414"), Description = "Roanwell He-157-006", Cost = 8790, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 109, DateTimeKind.Utc) },
                new { Id = 375, Guid = new Guid("f89992f3-ae29-45a4-bb32-9bc248d27cdb"), Description = "Roccat Kave XTD", Cost = 295, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 138, DateTimeKind.Utc) },
                new { Id = 376, Guid = new Guid("2760e5a7-9603-455e-bf59-f88e2ca27820"), Description = "RockPapa WKD80", Cost = 1798, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 167, DateTimeKind.Utc) },
                new { Id = 377, Guid = new Guid("773ba40b-d772-4205-9893-298c8e473016"), Description = "Roland RH-300", Cost = 8525, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 198, DateTimeKind.Utc) },
                new { Id = 378, Guid = new Guid("6d7c6715-cbcb-4b1e-8882-ece88e2041c7"), Description = "Sades R3", Cost = 5701, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 230, DateTimeKind.Utc) },
                new { Id = 379, Guid = new Guid("f70fb42e-93ec-433c-9a61-4aa1e2d21b46"), Description = "Samson Z55", Cost = 7653, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 262, DateTimeKind.Utc) },
                new { Id = 380, Guid = new Guid("fc237b29-be26-428c-9161-ab6a34531a27"), Description = "Samsung Galaxy Buds+", Cost = 9604, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 292, DateTimeKind.Utc) },
                new { Id = 381, Guid = new Guid("5b8dc44b-2163-4c23-b3cf-106c94305fc4"), Description = "Senal SMH-1000", Cost = 1557, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 322, DateTimeKind.Utc) },
                new { Id = 382, Guid = new Guid("ae5798e4-dcce-4d6a-813f-746115fe0c4b"), Description = "Senicc A2I", Cost = 3509, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 354, DateTimeKind.Utc) },
                new { Id = 383, Guid = new Guid("b51fc0b6-3e65-43bf-9a43-487dffb2585a"), Description = "Sennheiser HD 820", Cost = 237, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 384, DateTimeKind.Utc) },
                new { Id = 384, Guid = new Guid("93dea0e9-d5fc-4320-ae8f-6acba3287891"), Description = "Sentey Warp Pro LS-4421", Cost = 6963, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 414, DateTimeKind.Utc) },
                new { Id = 385, Guid = new Guid("6c223564-3c4c-4752-a90e-ad3874bc97eb"), Description = "Shenzhen Grandsun 233621", Cost = 3691, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 443, DateTimeKind.Utc) },
                new { Id = 386, Guid = new Guid("fdc53a88-fd1e-432a-8879-a437f0287c70"), Description = "Shure SRH1840", Cost = 419, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 473, DateTimeKind.Utc) },
                new { Id = 387, Guid = new Guid("6d9d94c9-b680-4f78-a1ed-0a87423d8857"), Description = "Sigtronics Corporation S-20 PNR", Cost = 1923, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 503, DateTimeKind.Utc) },
                new { Id = 388, Guid = new Guid("7da2b7eb-ef2f-4ca4-bf88-6a10ca94fcab"), Description = "Skullcandy Crusher", Cost = 9098, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 535, DateTimeKind.Utc) },
                new { Id = 389, Guid = new Guid("cc71cbe0-db24-4130-b7c7-227b6aebf9e6"), Description = "SMS Audio On-Ear Wireless Sport", Cost = 1499, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 571, DateTimeKind.Utc) },
                new { Id = 390, Guid = new Guid("727cac01-f02b-4883-a2d8-abed5017e60a"), Description = "Sol Republic Soundtrack Pro", Cost = 9123, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 604, DateTimeKind.Utc) },
                new { Id = 391, Guid = new Guid("19e37099-992d-41ce-9b33-5a7fdf999374"), Description = "Sonetics APX375", Cost = 6299, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 635, DateTimeKind.Utc) },
                new { Id = 392, Guid = new Guid("57a963f1-cb6f-48be-90ee-223ef0e99f3d"), Description = "Sony WH-1000XM3", Cost = 8251, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 665, DateTimeKind.Utc) },
                new { Id = 393, Guid = new Guid("7307a083-877b-4613-981a-8fdda7ee5755"), Description = "SoundMagic E80C", Cost = 4979, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 695, DateTimeKind.Utc) },
                new { Id = 394, Guid = new Guid("7b9638c0-2e98-42d1-b810-fcd98063ad0c"), Description = "SoundPeats Q30", Cost = 6930, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 727, DateTimeKind.Utc) },
                new { Id = 395, Guid = new Guid("226e87f8-a3c6-42df-b972-9321176c22da"), Description = "SoundWhiz Turbo", Cost = 4107, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 760, DateTimeKind.Utc) },
                new { Id = 396, Guid = new Guid("e72ee904-0592-479c-a3b6-ca2a0c470eb8"), Description = "Stanton DJ PRO 3000", Cost = 1732, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 793, DateTimeKind.Utc) },
                new { Id = 397, Guid = new Guid("d177e2b0-b789-40aa-b076-8e4f040caf91"), Description = "Stax Earspeakers SR-009S", Cost = 4580, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 829, DateTimeKind.Utc) },
                new { Id = 398, Guid = new Guid("03d736d3-d337-4b32-8e00-83929f27cae6"), Description = "SteelSeries Arctis Pro", Cost = 2205, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 862, DateTimeKind.Utc) },
                new { Id = 399, Guid = new Guid("11961483-03da-46d9-b316-fc70b7bbe2b8"), Description = "Sterling Audio S400", Cost = 9381, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 894, DateTimeKind.Utc) },
                new { Id = 400, Guid = new Guid("36623f58-6b35-4723-b3aa-e51d89da0759"), Description = "Superlux HD681", Cost = 3127, CategoryId = 8, UpdatedTime = new DateTime(2021, 2, 6, 8, 41, 16, 932, DateTimeKind.Utc) }
                );
                });

            modelBuilder.Entity("Catalog.Api.Database.Models.CatalogItemDto", b =>
                {
                    b.HasOne("Catalog.Api.Database.Models.CatalogCategoryDto", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
